### ISSUE TITLE
Error popup after clicking Change Avatar

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1009]
### Observed/problematic behavior

Error popup after clicking Change Avatar

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/59464084/200202967-5e404f6d-3c73-44aa-ac0b-a493811b4b07.png">

### Expected behavior

No error popup

### Steps to reproduce

I created a new account and clicked change avatar

**Comment by MiniDigger** [comment]
> Access to fetch at 'https://hangarcdn.papermc.dev/images/23/23724776CA648898BE4BE9BD31932A7D.webp' (redirected from 'https://hangarauth.papermc.dev/avatar/d7352a8b-7959-483e-a51f-d38dcf388daf') from origin 'https://hangarauth.papermc.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by MiniDigger** [comment]
set cors rules on b2, purged cf cache, fixed now

**Comment by lokka30** [comment]
Thanks, fixed on my end. 👍🏻
