### ISSUE TITLE
Unable to change avatar of an organisation

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1010]
### Observed/problematic behavior

Unable to change avatar of an organisation
![image](https://user-images.githubusercontent.com/59464084/200204335-c9d4066f-6afb-4ce9-af57-6acf76899564.png)

### Expected behavior

Avatar should save successfully

### Steps to reproduce

- Create an org
- Attempt to upload avatar

**Comment by lokka30** [comment]
I'm still getting the same error, @MiniDigger.

**Comment by lokka30** [comment]
Having the same error notification but I am now able to change the avatar successfully.

**Comment by MiniDigger** [comment]
can you test again?

**Comment by lokka30** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59464084/202878051-6e7ca5da-3f4b-4f2b-8f7c-63dcca5bc4ba.png">

Image doesn't change and error notification appears

**Comment by MiniDigger** [comment]
> Access to fetch at 'https://hangarauth.papermc.dev/avatar/user/HiddenOrgOnMyProfile' from origin 'https://hangar.papermc.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

**Comment by MiniDigger** [comment]
reee
> Access to fetch at 'https://hangarcdn.papermc.dev/images/61/612982169A864550723FB60807883A93.webp' (redirected from 'https://hangarauth.papermc.dev/avatar/user/HiddenOrgOnMyProfile') from origin 'https://hangar.papermc.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by MiniDigger** [comment]
no way to fix this other than allowing all origins

**Comment by MiniDigger** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=154967

**Comment by MiniDigger** [comment]
allowed *, purged cache, fixed.
![https://i.imgur.com/CqSJn94.png](https://i.imgur.com/CqSJn94.png)

**Comment by lokka30** [comment]
Confirmed fixed on my end 👍🏻
