### ISSUE TITLE
Logins do not seem to be persistent, sometimes.

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1016]
### Observed/problematic behavior

# Note: Unable to consistently reproduce.

When closing all Hangar tabs and then opening a new Hangar tab on my web browser, Hangar wants me to log in again.

### Expected behavior

Logins persist for some duration such as what occurs on GitHub, Spigot, etc.

### Steps to reproduce

- Open Hangar tab
- Login
- Close Hangar tab
- Wait a short period of time
- Open Hangar tab
- Hangar requests for login.

**Comment by MiniDigger** [comment]
I would blame this on cookie settings, the hangar session is valid for a month (but the hangar refresh token and the ory kratos session)
only hydra (consent) is a session token, but we skip that for hangar anyways.
closing for now.
