### ISSUE TITLE
Unable to edit description on my resource

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1019]
### Observed/problematic behavior

Edit button is not displaying on my resource

### Expected behavior

Edit button should display on my resource

### Steps to reproduce

Create a resource. I used the Markdown to BBCode converter, I think that might have caused the issue since this does not happen on my other resource which I did not use it for.

### Other

![Screenshot](https://media.discordapp.net/attachments/859516358281396234/1040210914630180914/image.png)

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/Hangar/blob/master/backend/src/main/java/io/papermc/hangar/model/common/roles/ProjectRole.java#L19

**Comment by lokka30** [comment]
I still don't have an edit button – can anyone reproduce? 🙂

**Comment by lokka30** [comment]
Update: Mini and I discovered I have the permission string `111` for that resource page.

[Link to conversation on the Hangar Discord](https://discord.com/channels/855123416889163777/859516358281396234/1043538809100447775)

**Comment by MiniDigger** [comment]
![https://cdn.discordapp.com/attachments/859516358281396234/1043540899076001862/image.png](https://cdn.discordapp.com/attachments/859516358281396234/1043540899076001862/image.png)
https://hangar.papermc.dev/api/v1/permissions?author=lokka30&slug=WWWWWWWWWWWWWWWWWWWWWWWWW

misses edit perm

**Comment by MiniDigger** [comment]
fixed

**Comment by lokka30** [comment]
Thanks, fixed on my end 👍🏻
