### ISSUE TITLE
Invalid license name not reported to user

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1020]
### Observed/problematic behavior

When the user inputs an invalid license name it is not shown to the user. Resource creation fails in the end without the given reason.

### Expected behavior

Hangar informs the user that they have entered an invalid license name.

### Steps to reproduce

- Create a resource.
- use the 'other' license type
- enter a long, obviously invalid name with lots of characters or something.
- proceed through the resource creation process and it should fail

### Other

![image](https://user-images.githubusercontent.com/59464084/201071007-53a69043-0268-4f33-af45-aef216d8392f.png)

**Comment by kennytv** [comment]
https://github.com/HangarMC/Hangar/commit/1c7b8be3ce5275a35e5b2fb70ac8ddb315dd1d85
