### ISSUE TITLE
Login button returns 404 with a fresh site session

### ISSUE THREAD

**Issue by AnttiMK** [HangarMC/Hangar#1023]
### Observed/problematic behavior

The login button gives you a `404 page not found` if you have a "fresh" site session (aka the first time you press it after clearing session cookies or whatever). If you go back and press it again, it correctly takes you to the login page.

### Expected behavior

To be taken directly to the login page.

### Steps to reproduce

1. Open incognito/somehow whip up a fresh session
2. Press login
3. Observe yourself looking at a 404 page

### Other

![unknown-2](https://user-images.githubusercontent.com/13612979/201452429-dd8a3868-b391-4755-a03e-af1b32f135bc.png)
Image taken a couple of weeks ago, but I assume the issue is still the same.

**Comment by MiniDigger** [comment]
this a really weird one and I can't reliably reproduce it, but I could reproduce it once (so did @lokka30).

I have pushed (and deployed) some code that maybe addresses this and will close this issue, if you can repro again I will need to look into this deeper...
https://github.com/HangarMC/HangarAuth/commit/2b2fe9131e16f8027cdbdb67a9c813ea105233ea
