### ISSUE TITLE
Unable to change existing resource icon

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1024]
### Observed/problematic behavior

Error notification received and no avatar change happened

![image](https://user-images.githubusercontent.com/59464084/201457374-bd016fa5-cf75-42a5-afd7-cf170b577446.png)

### Expected behavior

Avatar change happens successfully with no errors

### Steps to reproduce

1. Upload a resource
2. Upload an icon for it
3. Attempt to change the icon or reset it 🐞

### Other

Resource tested: https://hangar.papermc.dev/HarshDRMPluginStudio/-----essentials-reborn-sk#

**Comment by lokka30** [comment]
Interesting, the avatar change appeared after a while

**Comment by MiniDigger** [comment]
> Interesting, the avatar change appeared after a while

make sense, this 500 is caused by trying to purge the image cache in auth, but failing

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/HangarAuth/commit/ec7511c9cd9c776c1f9d6aed956239f899dab059

**Comment by lokka30** [comment]
Same issue still persists. I am able to change the icon of the resource although it gives me an Internal Server Error

![image](https://user-images.githubusercontent.com/59464084/202878022-beec868a-1b06-47f6-bd53-11b611d377ea.png)
