### ISSUE TITLE
Unable to edit the sponsors area in resource pages

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1029]
### Observed/problematic behavior

Unable to edit the sponsors area in resource pages

The box has an edit button where the user can type in a message. Changes are discarded, not saved.

### Expected behavior

Able to edit the sponsors area in resource pages. The changes are saved, not discarded.

### Steps to reproduce

Create a resource page and attempt to edit the Sponsors section.

**Comment by MiniDigger** [comment]
the changes are saved in the backend but require a refresh of the frontend, investigating

**Comment by lokka30** [comment]
Confirmed fixed 👍🏻
