### ISSUE TITLE
Not listed on the authors page

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1030]
I have created a bunch of resources on Hangar via my own account and also in organizations. None of these are listed on [Authors](https://hangar.papermc.dev/authors).
It is currently only showing the automatically generated sample resources.

**Comment by Machine-Maker** [comment]
Should be all owners of a project where the visibility of the project isn't "NEW". It's also cached, but that should be being cleared when a new project is created.

**Comment by MiniDigger** [comment]
pagination is client side only, like it was on project list

**Comment by lokka30** [comment]
Confirmed fixed on my end 👍🏻
