### ISSUE TITLE
Massive view counts

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1031]
### Observed/problematic behavior

On all of the resources, there is a massive view count number

### Expected behavior

View counts are more realistic

### Steps to reproduce

View any resource page currently on Hangar

**Comment by MiniDigger** [comment]
something funky is going on here
![https://i.imgur.com/4wBtYUz.png](https://i.imgur.com/4wBtYUz.png)

**Comment by MiniDigger** [comment]
???
![https://i.imgur.com/l1bQ0sH.png](https://i.imgur.com/l1bQ0sH.png)

**Comment by MiniDigger** [comment]
will be done via #1040 instead
