### ISSUE TITLE
Delete organization

### ISSUE THREAD

**Issue by Phoenix616** [HangarMC/Hangar#1045]
### Is your feature request related to a problem?

A way to delete an organization that you own.

### Describe the solution you'd like.

Deletion button on the organization (settings) page. Ideally with a warning about lost resources, maybe even a way to specify which user/org they should be moved to or if they should be deleted as well.

Maybe with manual staff approval to avoid abuse.

### Describe alternatives you've considered.

Pestering staff members 👀

**Comment by SlimeDog** [comment]
Alternative for resources: Require that projects owned by the organization be removed or reassigned (manually) before organization deletion is allowed.
