### ISSUE TITLE
Unable to upload a file in create version

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1048]
### Observed/problematic behavior

Unable to create version using an uploaded file. External URL worked but not uploading directly. File seems to have disappeared when I went back to the page shortly after completing the rest of the version information.

### Expected behavior

Expected the file to upload and stay throughout the duration of the version update being written and posted

### Steps to reproduce

Create a version on your project, upload a file, try to save/publish the version and it won't work

### Other

> MiniDigger | Martin — Today at 09:33
> Make an issue, I need to look at that flow anyway because of file size system
> Somebody tried uploading a 25mb jar and undertow wasn't happy about it 😂

**Comment by MiniDigger** [comment]
lemme summaries my thoughts here so I don't forget til next week:
* files are kept for 30min, LOCALLY
* if instance count > 1, it becomes a gamble if your first request to upload the file and the second request to create the version both hit the same instance
* only option is we need to move pending files into s3 too

**Comment by kennytv** [comment]
Possibly probably fixed by https://github.com/HangarMC/Hangar/commit/e3520d55783fff698e09dba44d53f18fea4bbb85

**Comment by lokka30** [comment]
> Possibly probably fixed by [e3520d5](https://github.com/HangarMC/Hangar/commit/e3520d55783fff698e09dba44d53f18fea4bbb85)

It allows me to upload a file if I fill out the form at lightspeed thereafter :)
There still seems to be a very fast expiry on the file upload

**Comment by MiniDigger** [comment]
Expiry is days now, what exactly do you see?

**Comment by kennytv** [comment]
The default branch is staging at hangar.papermc.dev; only once the master branch is rebased do you see these fixes on our main site

**Comment by lokka30** [comment]
Thanks, I was using the production branch, I'll check if it's fixed on my end soon

**Comment by lokka30** [comment]
Confirmed resolved on my end. Thanks guys!
