### ISSUE TITLE
Cannot upload project icon

### ISSUE THREAD

**Issue by Phoenix616** [HangarMC/Hangar#1049]
### Observed/problematic behavior

When trying to upload a logo image as a project icon the "Upload"-button never becomes interactable after adding an image in the file field.

Tested both on Chromium and latest Firefox Developer Edition with multiple different png files.

Tested on both "release" and staging.

### Expected behavior

The upload button to become active and an icon being able to get uploaded.

### Steps to reproduce

Try to change project icon in settings.

**Comment by Machine-Maker** [comment]
Should be significantly improved on staging now.

**Comment by Phoenix616** [comment]
Getting an "Error while uploading avatar" now on staging.
