### ISSUE TITLE
Add ability to add more/arbitrary donation link for donation button

### ISSUE THREAD

**Issue by Phoenix616** [HangarMC/Hangar#1050]
### Is your feature request related to a problem?

Currently only raw PayPal buttons are supported for donating. It would be good to also allow platforms like GitHub sponsors, Patreon, Ko-Fi, or even a third party donation site (e.g. I collect all options on my own site)

### Describe the solution you'd like.

A way to add multiple different donation options or, if only one button is desired, a way to link options other than just PayPal (e.g. by simply allowing arbitrary links)

### Describe alternatives you've considered.

Adding donation info into the text which isn't as visible as the donate button.

**Comment by MiniDigger** [comment]
I think I went with this complicated paypal setup since I wanted hangar to track donations for you so that you can paypal release channels or something, I think ill just disable the paypal shit for now (its linked to sandbox anyways)

the easier solution then is to just have a list of links with nice icons.

**Comment by SlimeDog** [comment]
> the easier solution then is to just have a list of links with nice icons.

More than sufficient.

**Comment by Phoenix616** [comment]
> paypal release channels

Sounds like an interesting idea but would ideally support other platforms too instead of only PayPal (e.g. Patreon, ko-fi, GitHub Sponsors, ...)

**Comment by SlimeDog** [comment]
I just added a `DONATE` button in the `Sponsor` field. For [example](https://hangar.papermc.io/SlimeDog/AggressiveAnimals). Is that kosher?

**Comment by SlimeDog** [comment]
New links management looks good. Thanks.
