### ISSUE TITLE
Sort lists caseless

### ISSUE THREAD

**Issue by SlimeDog** [HangarMC/Hangar#1053]
### Observed/problematic behavior

Lists are sorted alphabetically upper case first, followed by lower case. Lists should be sorted caseless. Examples:
- Authors
- Team

### Expected behavior

Lists sorted caseless.

### Steps to reproduce

Sort any alphabetic list. Results are sorted upper case first, followed by lower case.

**Comment by SlimeDog** [comment]
Projects list?

**Comment by MiniDigger** [comment]
you mean on start page? ![https://i.imgur.com/i8whlvb.png](https://i.imgur.com/i8whlvb.png)

**Comment by MiniDigger** [comment]
oh on profile? mmh, idk what the right sort there would be, I guess we need to export a sort button there too

**Comment by SlimeDog** [comment]
On the per-author list of projects.

![Screen Shot 2022-12-28 at 3 22 44 PM](https://user-images.githubusercontent.com/17748923/209884352-928b587b-342f-4ade-8fec-1160d8d89910.png)

**Comment by MiniDigger** [comment]
implemented now and deployed to staging: https://hangar.papermc.dev/lokka30

**Comment by SlimeDog** [comment]
Hmmm. https://hangar.papermc.dev/Hans_Moleman109

![Screen Shot 2022-12-28 at 5 10 40 PM](https://user-images.githubusercontent.com/17748923/209890904-74b8cbb6-03bd-45a9-8b06-b39bd98559d7.png)
