### ISSUE TITLE
Old project icon sticks around when switching search pages

### ISSUE THREAD

**Issue by NoahvdAa** [HangarMC/Hangar#1057]
### Observed/problematic behavior

When switching search pages, the old icons stay around for a bit until the new one is loaded, as shown in the gif below.

![](https://i.noah.pm/IMCPO5.gif)

### Expected behavior

The image either disappears or shows the alt text while loading, which is what happens when you refresh the page:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/44026893/209558500-83241b38-0a2f-4bc3-9e21-648c2a680fdc.png">

### Steps to reproduce

Switch search pages and look at the icons

### Other

My theory as to why this is happening is that Vue is somehow reusing the img elements, causing the old image to be displayed until the new one is loaded.

**Comment by kennytv** [comment]
https://github.com/HangarMC/Hangar/commit/58acab3bc83072039c5c27f3bcbc985154fab62a
