### ISSUE TITLE
Import projects from spigot

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#1068]
simple updated spigots api to include all kinda info that can be used to create projects and even versions:
https://api.spigotmc.org/simple/0.2/index.php?action=getResourcesByAuthor&id=100356&&page=1
https://api.spigotmc.org/simple/0.2/index.php?action=getResourceUpdates&id=28140&page=1

we could build an importer that lists all projects, allows the user to select which ones to import from a list, allows to change project names there, create all projects and then have a list of steps the user should do (validate project page, upload a jar, etc)

**Comment by MiniDigger** [comment]
validation needs work
error handling on last page seems bork
license stuff seems bork (maybe the util stuff is stupid?)

**Comment by MiniDigger** [comment]
add pagination for more than 10 resources?

**Comment by kennytv** [comment]
Fine as is imo, just debouncing needs fixing

**Comment by MiniDigger** [comment]
debouncing was fixed https://github.com/HangarMC/Hangar/commit/f05b25e1113ba909c36ec3485f369cd21c69593c
