### ISSUE TITLE
Homepage Issue on mobile (IOS Safari)

### ISSUE THREAD

**Issue by TureBentzin** [HangarMC/Hangar#1078]
### Observed/problematic behavior

Entering hangar via IOS Safari results in `{search_term_string}` being auto-filled into the search bar.
Screenshot (misusing Discord here):
https://cdn.discordapp.com/attachments/683623330254815262/1062459269577986058/image.png

### Expected behavior

It stays empty

### Steps to reproduce

Open Safari (latest version)
Open Hangar

**Comment by MiniDigger** [comment]
can't repro, pls include more steps (how did you access hangar, what decide/browser version, does it happen if you just manually enter the url, etc)

**Comment by MiniDigger** [comment]
(fwiw that search term string thing is a thing for google to display a search box in the SERP, which google right now doesn't even serve)
