### ISSUE TITLE
Browser back pulldown displays incorrect user profile

### ISSUE THREAD

**Issue by SlimeDog** [HangarMC/Hangar#1089]
### Observed/problematic behavior

User profile page content is not updated after browser `back pulldown`

### Expected behavior

Display correct page content

### Steps to reproduce

- Navigate from storage link to user profile page, in my case https://hangar.papermc.io/SlimeDog?page=0&sort=slug
- Navigate to [`Authors`](https://hangar.papermc.io/authors)
- Navigate to a different author, for example [TureBentzin](https://hangar.papermc.io/TureBentzin)
- Using `back pulldown`, return to original page (ie., back two pages)
- URL reports https://hangar.papermc.io/SlimeDog?page=0&sort=slug but page content is not updated, so displays TureBentzin profile
- Refresh page (CMD-R) to reveal correct page content

### Other

Browser version: Chrome Version 110.0.5481.77 (Official Build) (x86_64)
OS version: MacOS Monterey 12.6.2

Hangar prod version
```
This instance is running [Hangar](https://github.com/HangarMC/Hangar) 0.0.1-SNAPSHOT

The most recent commit is [6ec2b93](https://github.com/HangarMC/Hangar/commit/6ec2b932b139f4e9612080f5a49d485b7d2625c1) by Nassim Jahnke at 2023-02-14-13:48:38 with message:
Add colored tag display in role settings
```

**Comment by MiniDigger** [comment]
this isnt on us, browser back loads the old html, it doesnt make a new request, there is something we can do.
