### ISSUE TITLE
BBCode -> Markdown Converter issues

### ISSUE THREAD

**Issue by Phoenix616** [HangarMC/Hangar#1090]
### Observed/problematic behavior

Tried to convert bbCode from Paper forum releases

- `’` is converted to `?` (this is the equivalent to `'` in some keyboard layouts)
- `❤` (and possible other unicode chars) are converted to `?`
- `[HEADING=2]...[/HEADING]` will stay the same and not be converted

### Expected behavior

- `’` stays the same
- `❤` stays the same
- `[HEADING=2]...[/HEADING]` will be convert to `##` (and the other levels according to the heading value)

### Steps to reproduce

Put the previously mentioned chars into [the converter](https://hangar.papermc.io/tools/bbcode).

E.g. this text:

```
[HEADING=2]Sub heading[/HEADING]
The converter doesn’t ❤ me :(
```

**Comment by Phoenix616** [comment]
@kennytv  The commit doesn't seem to address the Heading issues as far as I can tell? Or was that related? (Sorry for posting both in one issue :S)

**Comment by kennytv** [comment]
https://github.com/HangarMC/Hangar/commit/34e843af3d2d03ece3a0a50a6b82a466a24125b1

**Comment by Phoenix616** [comment]
Yeah, found that just now. Sorry ^^'
