### ISSUE TITLE
Support non semantic versioning

### ISSUE THREAD

**Issue by AuroraLS3** [HangarMC/Hangar#1096]
### Is your feature request related to a problem?

My versioning scheme contains a build version that is changed on every commit automatically so that I don't need to update it. 

### Describe the solution you'd like.

I'd like to keep the build version separated with text eg. `5.5 build 2176`, where 5.5 is the semantic version and 2176 is the build version.

### Describe alternatives you've considered.

Using `5.5.2176` is currently enforced by the system. This may be confusing when the semantic version increases, since the build version is never reset (eg. `5.5.2176` -> `5.6.2182`)

**Comment by jpenilla** [comment]
semantic versioning allows build metadata after a `+`, `5.5+build.2176` should be valid

**Comment by AuroraLS3** [comment]
Yep that works. Thanks
