### ISSUE TITLE
Maximum project name length

### ISSUE THREAD

**Issue by Djaytan** [HangarMC/Hangar#1100]
### Is your feature request related to a problem?

The name of my plugin: JobsReborn-PatchPlaceBreak [Addon]

Unfortunately, the length is of 36 characters, which exceeds the limit of 25 characters imposed by Hangar.

Even by removing the "[Addon]" part this remains not enough since the remaining length is 26 characters.

On Spigot typically I don't have this issue: https://www.spigotmc.org/resources/jobsreborn-patchplacebreak-addon.102779/

### Describe the solution you'd like.

Having a limit increased to like 40 characters to allow projects with long names. Even having 50 characters would not be a so big issue IMHO, but in fact you are in a better position than me to choice between 40 and 50. I need 36 characters for my project, so both are fine for me

### Describe alternatives you've considered.

No alternative found

**Comment by TureBentzin** [comment]
![grafik](https://user-images.githubusercontent.com/38729194/223718557-d66e0921-dcf6-47b0-bc45-021b9269e2c3.png)
Thats how 50 could look like, but it may encourage misusing the name as a description field...

**Comment by Djaytan** [comment]
So maybe not 50
But below 40 seems too strict for me
A least 35, but not less

**Comment by kennytv** [comment]
I increased it to 28, but it'll stay that way until we see a reasonable case for 30 or larger. You're not supposed to add suffixes to the project name, being an addon etc. will likely be handled with a tagging system

**Comment by Djaytan** [comment]
Thanks @kennytv!

Is it possible to rename a project so?

**Comment by Djaytan** [comment]
Done :)
