### ISSUE TITLE
Spigot description page not properly imported

### ISSUE THREAD

**Issue by Djaytan** [HangarMC/Hangar#1101]
### Observed/problematic behavior

Here is the link of the page: https://hangar.papermc.io/Djaytan/JobsRebornPatchPlaceBreak

I will not update for now in order to let you inspect the result.

![image](https://user-images.githubusercontent.com/26904516/223553465-eed050c4-65b3-4e7a-8ce9-8d72ed8c3691.png)

Corresponding code generated:
```
<center>
# A place-and-break patch extension of [JobsReborn](https://www.spigotmc.org/resources/jobs-reborn.4216/)
</center>
```

![image](https://user-images.githubusercontent.com/26904516/223553508-d15f681f-64fa-4ebd-bc13-2cf7053d4f02.png)

```
**### Donation
**
If you appreciate my work and want to support me, then thank you a lot! It will also give me the motivation to share new works.
```

Seems that only the upper and lower parts are impacted, the rest between has been nicely converted

### Expected behavior

Spigot page completly imported without any formatting issue

### Steps to reproduce

Create a new project from a Spigot one

### Other

**Comment by MiniDigger** [comment]
the bbconverter will never be perfect, bbcode is too cursed for that. I did a few improvements, but that center at the top you have to fix yourself.
