### ISSUE TITLE
Plugin tags

### ISSUE THREAD

**Issue by olijeffers0n** [HangarMC/Hangar#1106]
### Is your feature request related to a problem?

Folia is gonna be very seperate to paper, so some sort of folia platform / folia badge is probably in order 

### Describe the solution you'd like.

Maybe a badge for folia support etc.

### Describe alternatives you've considered.

Just putting it in the title is the only way other than just supporting both.

**Comment by kennytv** [comment]
Just needs the ability to filter on the homepage now
