### ISSUE TITLE
Sometimes the WEB Page is not loading when clicked on a link

### ISSUE THREAD

**Issue by TheMeinerLP** [HangarMC/Hangar#1110]
### Observed/problematic behavior

![image](https://user-images.githubusercontent.com/6745190/225631401-159e428e-dab5-49e5-929d-a6c07a6fa791.png)
Compare url and visual what I have posted. 

Metadata:
![image](https://user-images.githubusercontent.com/6745190/225631622-3e131026-e925-40f3-a51b-6071b2d022b4.png)

### Expected behavior

Must be loaded. 

### Steps to reproduce

1. Use the search for a plugin.
2. Click on author/plugin and wait.

**Comment by MiniDigger** [comment]
does this still occur?

**Comment by TheMeinerLP** [comment]
Let me check that again

**Comment by TheMeinerLP** [comment]
Works greate i think was a caching issue. 
I close it
