### ISSUE TITLE
External content in markdown not proxied

### ISSUE THREAD

**Issue by OskarZyg** [HangarMC/Hangar#1112]
### Observed/problematic behavior

Images in markdown files are not proxied. This creates an opportunity for malicious tracking.
![image](https://user-images.githubusercontent.com/56176746/225723284-8846f64e-8c3d-4e9f-8771-5f45167aa856.png)

### Expected behavior

Images should be proxied via a CDN.

### Steps to reproduce

N/A

**Comment by MiniDigger** [comment]
linkout also broke
https://github.com/HangarMC/Hangar/commit/130dcc730177d462342d531a1edc17a74dd39e7b
