### ISSUE TITLE
Left side of table has not vertical line

### ISSUE THREAD

**Issue by Andre601** [HangarMC/Hangar#1113]
### Observed/problematic behavior

The left side of a table doesn't have a vertical line.

![image](https://cdn.discordapp.com/attachments/859516358281396234/1086281857496256534/image.png)

### Expected behavior

The line should be there.

### Steps to reproduce

1. Make a table (i.e. using Markdown format).

**Comment by MiniDigger** [comment]
https://hangar.papermc.io/Andre_601/AdvancedServerList on firefox
