### ISSUE TITLE
Extra tab for automated extracted Permissions from Plugin.yml

### ISSUE THREAD

**Issue by TheMeinerLP** [HangarMC/Hangar#1115]
### Is your feature request related to a problem?

This feature is nice to have and is to against problems with no documented permissions but present.

### Describe the solution you'd like.

Add a module/checkbox a the plugin site inside of setting to auto extract permissions and display then in a extra between Versions and Docs.
![image](https://user-images.githubusercontent.com/6745190/226204900-d6e30241-4f7d-4000-b9ee-c8c5ddf7492d.png)
_I edit the html text for preview example_ 

### Describe alternatives you've considered.

Also possible is to add a section under docs with all permissions.
Example: 
![image](https://user-images.githubusercontent.com/6745190/226205125-616f7ca1-3fb7-414b-91cf-1b159d739ac5.png)

**Comment by kennytv** [comment]
There's a long list of other things that could be added in the bar, such as commands or config, but that's best done as another docs page considering it is still part of docs
