### ISSUE TITLE
External downloads are not marked as external downloads

### ISSUE THREAD

**Issue by BrycensRanch** [HangarMC/Hangar#1118]
### Observed/problematic behavior

With all this fancy jar scanning stuff I hear about - right now it has a fatal flaw, it doesn't indicate to end users that the download is NOT scanned with external downloads. I saw this with Geyser, where they're linking their CI because Hangar has jar size limit of 10MB, while I know good and well Geyser is a FATTTTT jar 

### Expected behavior

Maybe a warning like Spigot where it shows the download but you can easily tell at a simple glance it's external. No need to have a scary popup but just add some text or something, like our good friend Spigot 

### Steps to reproduce

Download Geyser Velocity which is 13MB. It links you to Geyser's CI artifacts - I thought this was a native download because I was directly linked to the geyser velocity jar - but it is not. It's from Jenkins. OLD MAN JENKINS!!

### Other

Screenshot: 
![msedge_RyRBxkvkny](https://user-images.githubusercontent.com/117921904/226997275-93e38408-fec2-43bb-a6f3-5a5d8875e56d.png)

**Comment by kennytv** [comment]
The exclamation mark next to the button is currently used for both unreviewed and external links (but showing only the "unreviewed" text if it is unreviewed), I think making those separate should solve this

**Comment by BrycensRanch** [comment]
Yeah I didn't even read the exclamation mark because it didn't look relevant/important

**Comment by kennytv** [comment]
https://github.com/HangarMC/Hangar/issues/1118
