### ISSUE TITLE
Universal Platform

### ISSUE THREAD

**Issue by BrycensRanch** [HangarMC/Hangar#1119]
### Is your feature request related to a problem?

Some plugins deploy universal jars that have all platform support in it. Ie Spigot support, Paper plugin support, Sponge, etc.

### Describe the solution you'd like.

Maybe it'd be a good idea to add an Enum for them too?

### Describe alternatives you've considered.

just linking every platform that's supported to the same universal jar or the platform-specific jar 

### Other

![image](https://user-images.githubusercontent.com/117921904/226997668-207a144c-d72b-40c7-80e7-a22c99c8a86c.png)

**Comment by kennytv** [comment]
This is a non-issue, the user will click on what they need, so it doesn't matter that all three are the same jar
