### ISSUE TITLE
Import Projects and CSS Issue with error message on MS Edge

### ISSUE THREAD

**Issue by BrycensRanch** [HangarMC/Hangar#1120]
### Observed/problematic behavior

Importing projects from our friends at SpigotMC is not working - it appears to be on Hangar's side as I can request it myself and get back the information.

### Expected behavior

Prompt to import all my plugins from SpigotMC to Hangar or an auth error because I'm not logged in the first place to even use this tool. Or maybe it'd be better to allow the user to import and then sign it to actually import it into Hangar, which would introduce a very user-friendly onboarding feature. 

### Steps to reproduce

Visit https://hangar.papermc.io/tools/importer

Type in "R0mvnly" 

Press enter 

and boom, error.

### Other

On Firefox:

https://user-images.githubusercontent.com/117921904/227039862-079b69d1-0fc2-44bb-9058-c4e78daed1ab.mp4

On MS Edge:

https://user-images.githubusercontent.com/117921904/227039914-d331edc4-a203-4286-b73c-a18f2a60a046.mp4
https://user-images.githubusercontent.com/117921904/227039891-54ea1f50-8095-4d3f-b9c1-799d47dc73bf.mp4

MS Edge console logs:  https://pastebin.com/PAsTzahc
FireFox console logs: https://pastebin.com/YG7tJ6EQ

What happens when I visit the URL myself instead: 

https://user-images.githubusercontent.com/117921904/227041043-266b3eb4-2f1d-423a-9304-bc07d86c5e13.mp4

Spigot profile: https://www.spigotmc.org/members/r0mvnly.460117/

**Comment by MiniDigger** [comment]
I cant repro this, can you try again?

**Comment by BrycensRanch** [comment]
> I cant repro this, can you try again?

Still can

https://streamable.com/tj0tah
