### ISSUE TITLE
Project-Import screen "Remove"-Button is misleading

### ISSUE THREAD

**Issue by TBlueF** [HangarMC/Hangar#1132]
### Observed/problematic behavior

I just spent a few minutes adding/fixing some project-details just to then click this button because I thought it would remove the logo so i can select a better one:
![image](https://user-images.githubusercontent.com/10765470/229909323-5056a1f7-dec9-44dc-b4af-67f9ca20f0b8.png)
turns out it just removes the project including all edits i made, without a warning :)

### Expected behavior

Either make it more clear that this button removes the project and is not associated with the Avatar, 
or maybe add some kind of warning/confirmation popup, especially if there are changes to the Project-description

### Steps to reproduce

- Start importing projects from SpigotMC
- Make valuable changes
- Accidentally click "Remove" ;D

**Comment by MiniDigger** [comment]
![https://i.imgur.com/pmM1ioe.png](https://i.imgur.com/pmM1ioe.png)
good enough
