### ISSUE TITLE
API endpoints with permission node always fail for anonymous tokens

### ISSUE THREAD

**Issue by JulianVennen** [HangarMC/Hangar#1143]
### Observed/problematic behavior

The API endpoint /pages/main/{author}/{slug} seems to always return 404 - Not Found errors.
e.g. https://hangar.papermc.io/api/v1/pages/main/Aternos/motdgg

The same problem seems to happen for the /pages/page endpoint, although I'm not sure how the paths there are supposed to work exactly. I tried "/", "/versions/1.3.4" and "versions/1.3.4" .

### Expected behavior

As this project does have a markdown description, it should return the markdown content.

### Steps to reproduce

Open https://hangar.papermc.io/api/v1/pages/main/Aternos/motdgg

### Other

I also tried this with ViaRewind to check if this problem is specific to our project and had the same problem.

**Comment by kennytv** [comment]
The problem is that the current permission voter only accepts authenticated connections
