### ISSUE TITLE
Add an option to re-send verification emails

### ISSUE THREAD

**Issue by hasankayra04** [HangarMC/Hangar#1153]
### Is your feature request related to a problem?

Sometimes mails do fail to send or to be received.

### Describe the solution you'd like.

Option to re-send verification emails.

### Describe alternatives you've considered.

None.

**Comment by MiniDigger** [comment]
you can attempt to resend once the old email expired.
do note that emails aren't being send right now because our email provider ratelimited us, we are working on resolving that.

**Comment by kennytv** [comment]
(Fixed the button not appearing, but the provider still won't send emails atm)
