### ISSUE TITLE
A way to change your email

### ISSUE THREAD

**Issue by AoElite** [HangarMC/Hangar#1155]
### Is your feature request related to a problem?

I'd like to change my email for my hanger account but I am unable to do so

### Describe the solution you'd like.

A way to change the email, like a button or something

### Describe alternatives you've considered.

You could create a new account but then your username & other information wouldn't transfer

**Comment by kennytv** [comment]
https://hangar.papermc.dev/auth/settings/account

**Comment by AoElite** [comment]
> https://hangar.papermc.io/auth/settings/account

@kennytv Editing your email in that text field doesn't do anything. It resets it right back. It won't send a confirmation to that new email.

**Comment by kennytv** [comment]
You need to also press "Save" and look for the notification that pops up
