### ISSUE TITLE
Add the ability to embed (YouTube) videos

### ISSUE THREAD

**Issue by MenschenToaster** [HangarMC/Hangar#1158]
### Is your feature request related to a problem?

Many plugins tend to have plugin reviews/showcases on YouTube or other video hosting platforms to show their users how their plugin works and lets users easily discover if the plugin is applicable to the user's requirements. On Hangar, these videos can not be embedded directly, which limits creator's ability to present their plugins. 

### Describe the solution you'd like.

Some form of embedding videos. Could be an implementation where iframes are allowed for e.g. embedded YouTube videos or the video just gets embedded when pasting the YouTube URL into the markdown editor. 

### Describe alternatives you've considered.

Just linking the videos for users to manually click on

**Comment by me4502** [comment]
The current partial support that gets eaten by the sanitiser also has a bug around the width/height parsing.

The following text will parse the `==450` as part of the `url` field rather than `height`, leading to the check to fail.

`![WorldEdit: Make a Mountain](https://youtu.be/72HlPD9CW10==450)`
