### ISSUE TITLE
Unclear org deletion validation

### ISSUE THREAD

**Issue by e-im** [HangarMC/Hangar#1159]
### Observed/problematic behavior

Org deletion modal requires a comment of at least 7 chars, validation is not made clear.

### Expected behavior

It should display why the delete button is disabled. Or, not require a comment at all.
Could also do something like requiring typing the org name to be extra sure but leave the comment as optional.

### Steps to reproduce

Create an org, attempt to delete it.

![](https://cdn.discordapp.com/attachments/859516358281396234/1099439358274179154/firefox_Gd0qkHCsaI.png)

### Other

https://github.com/HangarMC/Hangar/blob/1e6803f1b9882a0fa0e9b854787cbcac149d9576/frontend/src/components/modals/OrgDeleteModal.vue#L36

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/Hangar/commit/83e4c7fdb5a6251910e290bced71838914339ccc
