### ISSUE TITLE
Having a space in a resource version name causes an error

### ISSUE THREAD

**Issue by Pyrbu** [HangarMC/Hangar#1160]
### Observed/problematic behavior

Title

### Expected behavior

Some sort of warning telling me I can't do that before I exit that tab or allow spaces in the version names.

### Steps to reproduce

1) Begin creating a new resource version
2) Fill out all fields making sure to put a space in the version name
3) It errors with a message in the bottom right when you try to completely finish the version

**Comment by MiniDigger** [comment]
https://i.imgur.com/KlDTKVH.png
