### ISSUE TITLE
"Invalid request content" when trying to create a new release

### ISSUE THREAD

**Issue by Jack1424** [HangarMC/Hangar#1164]
### Observed/problematic behavior

When I try to create a new release (after filling out the changelog), nothing happens, and an error shows in the bottom right corner that says ": Invalid request content"

This occurs when I try to upload a file and when I try to link to an external download URL

### Expected behavior

Hangar should publish my release without showing any errors

### Steps to reproduce

Simply try to publish a release

**Comment by Jack1424** [comment]
Well, this problem no longer occurs. I think it had to do with Hangar letting me type in an invalid release name (it doesn't let me anymore).

**Comment by MiniDigger** [comment]
yes, that response is by the server side validation, no clue why it doesnt show the real validation message anymore tho and instead just shows this bad generic one instead
