### ISSUE TITLE
Project abandonment state?

### ISSUE THREAD

**Issue by Pheotis** [HangarMC/Hangar#1169]
Probably a super low priority idea, but I figured I'd pitch it anyways.

### Is your feature request related to a problem?
![image](https://user-images.githubusercontent.com/49039536/233815592-56dadaa3-e272-4d0e-8a48-e3060cb9c837.png)
Presently, it is only possible for a project to be deleted, transferred, and renamed.

If a developer lacks the time needed to continue a project, is unable to find someone to take it over, and wants to let the community know that it is no longer maintained, some sort of abandoned state might be beneficial.

Projects which are not maintained, but not marked as abandoned, can cause confusion.

### Describe the solution you'd like.

Abandoning a project would likely need to be an option directly above deleting the project.

Abandoning a project could do many things, potentially including some or all of the following:
- Displaying some sort of banner above the project, letting users know it is no longer maintained.
- Excluding the project from the home page's search bar (or putting it at the bottom of the results).
- Perhaps offering the developer the opportunity to pick another hangar project to suggest as a replacement?
  - "This project is no longer maintained. You may wish to try this  other project instead"
- Perhaps offering the developer the opportunity to offer the project up for adoption?
  - I.e. some sort of a system to list abandoned projects in need of new maintainers and their contacts?

### Describe alternatives you've considered.

The traditional way of doing this is simply making a giant red text banner at the top of the page stating "This project is abandoned; we suggest using (resource name) instead", but some sort of official support has several benefits:

- Cleaner.
- Prevents the search from getting clogged.
- Makes something like an adoption program possible.

**Comment by MiniDigger** [comment]
I guess this ties into https://github.com/HangarMC/Hangar/issues/384
I will close this as duplicate but we will consider your thoughts when working on that issue
