### ISSUE TITLE
Channel hover messages.

### ISSUE THREAD

**Issue by Pheotis** [HangarMC/Hangar#1170]
### Is your feature request related to a problem?

Channels are an amazing feature that support resource streams targeted at different use cases / user types.
Some use cases / user types may be difficult to describe within a tag's character limit.

For example, among our channels, we have Legacy (based on an old codebase) and ESR (extended support releases);
A user coming across our project for the first time may not be able to discern that simply from the tags shown (`Legacy` and `ESR`).

### Describe the solution you'd like.

On github, when creating a label, you are given the option to provide a quick explanation (which is shown when a user hovers):
![image](https://user-images.githubusercontent.com/49039536/233816236-3aa40466-44aa-4ac4-b32f-7c2f92da0272.png)

Channel tags are applied in a similar way to github's labels: would it be possible to make it so that, when editing a channel, one has the option of adding a description that shows up in a similar manner?

![image](https://user-images.githubusercontent.com/49039536/233816258-6501dcd3-82a5-42a8-9de9-3ffb5a8b1b41.png)

### Describe alternatives you've considered.

Another possible (albeit way worse) solution might be to display a short description besides the channels list on the versions page; this is far from ideal.

Another option might be to have overly verbose tag names, but something like `Versions-That-Receive-Limited-Maintenance-For-A-Long-Period-Of-Time` is unwieldy, ugly, and counterproductive.

**Comment by MiniDigger** [comment]
no pretty tooltip yet but I feel like its good enough
