### ISSUE TITLE
A way to search the authors page.

### ISSUE THREAD

**Issue by Pheotis** [HangarMC/Hangar#1172]
### Is your feature request related to a problem?

Presently, "Authors" is one of the three main tabs at the top of hangar.
![image](https://user-images.githubusercontent.com/49039536/233817048-36f375fb-102a-427c-948a-ecdc70660804.png)

It links to this page.
![image](https://user-images.githubusercontent.com/49039536/233817062-cc49fb9f-a3f1-49d2-9c3b-66f11b6a6741.png)

Although this page can be sorted alphabetically, by account age, and by number of resources, there is no search functionality.
![image](https://user-images.githubusercontent.com/49039536/233817070-df72fde0-3e5b-49a6-b8de-e4926b706fe4.png)

If someone only has a vague idea who they are looking for, sortation may not be enough.
Also, given that Hangar will likely eventually grow to the size of spigot's resource listing portal, it is not unreasonable to expect that Hangar may eventually have 25 000+ authors (who, under the present system, would then be listed under 1 000 pages -- too many to easily navigate, even when sorted).

### Describe the solution you'd like.

A search bar would probably be a good idea in the long term.

**Comment by MiniDigger** [comment]
fun fact, the admin view already supports filtering :D
![https://i.imgur.com/nZHlIuC.png](https://i.imgur.com/nZHlIuC.png)

**Comment by MiniDigger** [comment]
backend is done, needs frontend, but I g2g
