### ISSUE TITLE
Requirements for names not shown to user

### ISSUE THREAD

**Issue by 456dev** [HangarMC/Hangar#1179]
### Observed/problematic behavior

# Creating a project (invalid characters)
![image](https://user-images.githubusercontent.com/42748092/233844096-fefca737-cc68-42e9-9d2f-bbb4b55edb84.png)

# Creating a project (too short)
![image](https://user-images.githubusercontent.com/42748092/233844473-3bd5d3f3-8667-41c3-8594-af61bfd278cc.png)

# creating an org (invalid character)
![image](https://user-images.githubusercontent.com/42748092/233844441-e78b4ba8-f062-4e2e-b52c-92fbef67205e.png)

### Expected behavior

sensible user-facing errors on the text input

### Steps to reproduce

log in
https://hangar.papermc.dev/new
enter an invalid project name (with special characters / too short)
observe no good error, only "invalid"

**Comment by Canvas-cult** [comment]
Hi @the456gamer!
I would like to work on this.
