### ISSUE TITLE
Route permissions

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#118]
Each route needs to be checked to make sure only users with the proper permissions will be able to access it.

**Comment by Machine-Maker** [comment]
Done on frontend routes. Only need to do v1/v2 api routes.

**Comment by Machine-Maker** [comment]
k, this should be done. Gonna leave this open cause I think someone else should go over and check to make sure they all are permission'd correctly.

**Comment by MiniDigger** [comment]
todo: go over every route (intellij can help) and make sure all have routes perms
