### ISSUE TITLE
Pictures not fetched correctly

### ISSUE THREAD

**Issue by martijnpu** [HangarMC/Hangar#1187]
### Observed/problematic behavior

Picture is not consistent with the requested picture. Looks like the parameters are not passed through correctly.
See pictures in 'Steps to reproduce' and how I would expect it to see in ' Expected behavour'.

### Expected behavior

See the same picture as when the picture URL is visited.

https://img.shields.io/discord/755734170709524557?label=%7F&logo=discord&logoColor=%235865F2

![image](https://user-images.githubusercontent.com/38832167/233860082-ec5beb62-e770-40ee-af76-da49e144668f.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/38832167/233860019-6b7a6dae-2785-4ae0-9b5f-c32625380abc.png)

**Comment by MiniDigger** [comment]
![lol](https://i.imgur.com/nbJLSqn.png)
lol

**Comment by martijnpu** [comment]
Hi,

Today I saw the changes. It's already a lot better (The custom text is shown) however spaces are not formatted (%20)

![image](https://user-images.githubusercontent.com/38832167/234102315-325937ac-3ce3-4b24-a6eb-21a65a0ebb33.png)

**Comment by MiniDigger** [comment]
I don't fully understand it, but guess we can just add spaces here https://github.com/HangarMC/Hangar/commit/597e064dd33edf1e86c0963c38e7e05542816bff#diff-5a5fc02937e6db152fdb1e3ba8c2be7926b4a7481a14b612fadc3284d673cc35R52

**Comment by martijnpu** [comment]
It's a weird issue, but that would probably fix it.
Thanks already 😄

**Comment by MiniDigger** [comment]
done

**Comment by martijnpu** [comment]
It's looking all nice now. Thanks for the changes!
