### ISSUE TITLE
Social site details are not displayed anywhere

### ISSUE THREAD

**Issue by tadhgboyle** [HangarMC/Hangar#1192]
### Observed/problematic behavior

Information added here is not shown to profile visitors at all:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/26070412/233906957-45e7835a-cd7f-4c17-be2b-2cae6818b440.png">

Might fit nicely under the account tagline?
Additionally, maybe a "Personal" type would be nice to link to a portfolio site etc

### Expected behavior

A users social links displayed somewhere on their public profile

### Steps to reproduce

1. Add social details to your profile
2. See that they are lost to the void

**Comment by Aberdeener** [comment]
Might fit nicely under the account tagline?

**Comment by MiniDigger** [comment]
@darbyjack is working on this (I cant assign you for some reason)
