### ISSUE TITLE
Ability to sort versions and selection for the main download-button

### ISSUE THREAD

**Issue by eingruenesbeb** [HangarMC/Hangar#1196]
### Is your feature request related to a problem?

The problem is, that you currently can't reorder versions and the main download-button always refers to the latest version, that was uploaded.
I encountered this issue, when I uploaded some older versions of my plugin (for completeness's sake), as I uploaded the oldest version last. While the version number indicated the latest version, it's quite unintuitive, that it's at the very bottom. Additionally, when clicking the download button on the very top of the project's page, it downloads the version, that was uploaded most recently. 

This is an issue, for creators, that upload pre-existing projects, due to migrating to Hangar (or just making it available there), as they may upload versions in bulk and in any order.

### Describe the solution you'd like.

In my mind, the optimal solution and most intuitive solution for this would be to let people drag and drop the versions along the list.

For the download-button on the top-right of the project-page, there should be a settings option, to select a version.
A possible implementation of which could let one choose a release-channel and version. To not loose the default (and current) behavior, the options could be optional. If no channel is selected, the latest version (at the top of the list) is chosen, and if a channel, but no specific version is chose, the latest version of the specified channel is chosen.

### Describe alternatives you've considered.

There are probably many other ways, to improve this. For example, there could be a system, similar to Modrinth, with featured versions. (Also, their system of filtering for a specific version is a good idea.)

**Comment by kennytv** [comment]
I don't know any site that lets you create versions/releases in a non-chronological order, it doesn't seem like something that provides too much benefit vs. just uploading it the right order initially given it adds complexity both on the backend and visually
