### ISSUE TITLE
oAuth or API key scope limitting 

### ISSUE THREAD

**Issue by quiquelhappy** [HangarMC/Hangar#1198]
### Is your feature request related to a problem?

The only way of externally authenticating an user is via API keys, which apparently can be used to retrieve a JWT with full account access, including listing other API keys, which in my opinion shouldn't be allowed, because even if that API key is revoked, other API keys can be used to still have access to the platform without the user being aware of it.

### Describe the solution you'd like.

I think using oAuth would allow some flexibility for logging in on other websites. JWT would simply contain the scope value limiting the listing of other API keys, or maybe read-only, or read-and-write permissions.

### Describe alternatives you've considered.

Limitting the API keys would also be a viable option, but I think that API keys can remain having full access (other than listing other API keys, I don't think that's great for security). I don't think it would be great doe, IMO, implementing the oAuth flow should be prioritized in favor of adding key flexibility, just for the sake of focusing on new features hangar does not have yet.

### Other

I've been looking into this particularly because I'm building a package manager, that also allows for publishing on multiple platforms, and I'd like to store client-id specific access/refresh tokens rather than unlimited API keys, as it is more secure for users. I haven't looked deeply into this project yet, but I have great experience coding oAuth systems, so, if the authentication portion of this project is open, I'll try to take a look at it in the coming weeks and maybe Ill submit a PR.

**Comment by MiniDigger** [comment]
Please don't store any session or refresh tokens, that is internal API. API auth works using the API keys and only that. That is way more secure too.
API keys have tons of scopes already, what scope are you missing?

**Comment by quiquelhappy** [comment]
If that's the case, sorry about that, I was giving it a quick look during class and didn't see the scopes on the API. I probably overlooked them by accident, sorry for opening this issue then :). Still, an oauth flow may make it more friendly to connect accounts on web apps. Feel free to keep this opened if you think whether or not oauth is worth to implement

**Comment by MiniDigger** [comment]
There are no plans to use hangar as an oauth provider. The API keys should suffice for now, the allow you to specify what perms you want to give.
