### ISSUE TITLE
Unknown error when creating project

### ISSUE THREAD

**Issue by GabrielFJunkes** [HangarMC/Hangar#1211]
### Observed/problematic behavior

When importing a project from spigot and adding a link section and leaving empty, an unknown error occurs without telling me what it was wrong.

### Expected behavior

Telling me I had an empty link section

### Steps to reproduce

When importing a project (didnt test on creating one)
Add link section and leave empty
Try creating project and see the error

### Other

First image: the empty section (the second top section)
![image](https://user-images.githubusercontent.com/69057368/235328472-1092cd32-cfe5-426c-adc5-95e023cb9187.png)
Second image: the error
![image](https://user-images.githubusercontent.com/69057368/235328487-7aeca2ed-d443-4efa-bf30-3d45e48f4d84.png)

**Comment by MiniDigger** [comment]
should be addressed by https://github.com/HangarMC/Hangar/commit/a9846d1b6cced34e01f14d43c886a3efdaf25f26?

**Comment by GabrielFJunkes** [comment]
![image](https://user-images.githubusercontent.com/69057368/235360120-352c3551-8095-4d01-91a2-ab358bd29c36.png)
The toast shows the correct error, but not in the card.
Why allow the user to create multiple top sections if you cant have more than one?
