### ISSUE TITLE
Hangar API Documentation

### ISSUE THREAD

**Issue by GamerCoder215** [HangarMC/Hangar#1213]
### Is your feature request related to a problem?

Hello,

Is there any documentation for the Hangar API? I was looking through various menus and tabs to see if it was anywhere, so if it already exists then please point me to it.

If not, when can we expect documentation for the Hangar API?

### Describe the solution you'd like.

Documentation for the Hangar API

### Describe alternatives you've considered.

No Current Alternatives Exist

**Comment by MiniDigger** [comment]
the api docs are linked in the footer
https://hangar.papermc.io/api-docs
