### ISSUE TITLE
Images are not rendered anymore

### ISSUE THREAD

**Issue by martijnpu** [HangarMC/Hangar#1226]
### Observed/problematic behavior

A lot of pictures are not redered anymore.
Any example is this one: https://bstats.org/signatures/bukkit/PrefiX.svg
![image](https://user-images.githubusercontent.com/38832167/236686079-b3729280-cecb-4c52-8fec-2046bcce32f9.png)

But also all images that are fixed with #1187 are broken

### Expected behavior

That all pictures are working again: 
![image](https://user-images.githubusercontent.com/38832167/236686294-8a34f1ba-5cf1-4eaa-828d-b6b571984233.png)

### Steps to reproduce

Visit any page that used dynamic pictures and see that they are broken.
Examples:
- https://hangar.papermc.io/martijnpu/PrefiX
- https://hangar.papermc.io/CORE/CoreProtect#bstats

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/Hangar/commit/4ee03c7c9f8d95f5fb5889712fb1898156f15347

**Comment by MiniDigger** [comment]
(for the record, the broken bstats image on the coreprotect page isnt hangars fault, the linked image is broken)

**Comment by martijnpu** [comment]
Ah oke. 
I see it's also pushed to master already. Thank you for fixing this issue!
