### ISSUE TITLE
Owners Can't Star their Own Projects, but they can if they are under an Organization you own/manage

### ISSUE THREAD

**Issue by GamerCoder215** [HangarMC/Hangar#1228]
### Is your feature request related to a problem?

Currently, starring your own projects is disabled. However, you can star projects under organizations that you own, which is almost the same effect.

### Describe the solution you'd like.

Either allow us to start our own projects, or disable starring projects under organizations that you own (possibly also if you are an admin of).

### Describe alternatives you've considered.

No current Alternatives

### Other

![image](https://user-images.githubusercontent.com/54124162/236706135-aa714031-05b3-40b1-b0b6-467e8850fa5c.png)
![image](https://user-images.githubusercontent.com/54124162/236706121-5beaa5f6-3258-4c4c-bc7c-167fda21999d.png)

**Comment by Machine-Maker** [comment]
I think its fine to star your own project. Github also lets you do that also

**Comment by kennytv** [comment]
https://github.com/HangarMC/Hangar/commit/3704cdf46bb6e33ee52c7dd4bc5e51a8e9b04767
