### ISSUE TITLE
Projects API Endpoint query not working as intended

### ISSUE THREAD

**Issue by xMrAfonso** [HangarMC/Hangar#1239]
### Observed/problematic behavior

When setting the query of the projects endpoint, for instance, if I set the query to ViaVersion, I will get ViaVersion-Expansion as the first result.

### Expected behavior

Expected to get, in this example, the project ViaVersion as first result.

### Steps to reproduce

Like said previously, ViaVersion is an example where you get ViaVersion-Expansion.

Link: https://hangar.papermc.io/api/v1/projects?orderWithRelevance=true&limit=1&offset=0&q=viaversion

### Other

The issue can be caused because ViaVersion-Expansion has the keyword "viaversion" and is being prioritized over the original ViaVersion.

OrderWithRelevance seems to also have an impact, since if this is set to true, ViaVersion-Expansion will be returned, otherwise, if set to false, ViaBackwards will be returned.

Setting the category to slug, always returned ViaBackwards.

PS: This was only tested with ViaVersion.

**Comment by kennytv** [comment]
I removed the parameter as it wasn't an ideal metric. Instead, I would suggest sorting by stars, (recent) downloads, or (recent) views. Queries will always give exact matches at the top as well now, which you can toggle using a new `prioritizeExactMatch` parameter.
