### ISSUE TITLE
Release version not supported

### ISSUE THREAD

**Issue by Justman10000** [HangarMC/Hangar#1241]
### Observed/problematic behavior

When compiling this comes:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project hangar: Fatal error compiling: error: release version 17 not supported -> [Help 1]

### Expected behavior

The compiled .jar

### Steps to reproduce

1. Pull or Clone the repository
2. Try to compile

**Comment by electronicboy** [comment]
You need to update your java install (and, we should probably set up the toolchain...)

**Comment by Justman10000** [comment]
> You need to update your java install ~(and, we should probably set up the toolchain...)~

Well, the answer came quickly 😅! In fact, I have the latest Java 20

**Comment by electronicboy** [comment]
Output of 'javac -version'?

**Comment by Justman10000** [comment]
> ...double check the java version that is being used to run maven

java 20.0.1 2023-04-18

**Comment by Justman10000** [comment]
> ...double check the java version that is being used to run maven

java 20.0.1 2023-04-18
javac 20.0.1

**Comment by Justman10000** [comment]
@electronicboy

I still have the complete debug log here:

[log.txt](https://github.com/HangarMC/Hangar/files/11709745/log.txt)

**Comment by AnttiMK** [comment]
![image](https://github.com/HangarMC/Hangar/assets/13612979/9d735d7f-099b-499e-aac3-6c25a86e3ce0)
What are you running maven through? Whatever it is is making maven use Java 11

**Comment by Justman10000** [comment]
@electronicboy

And that is closed because?

**Comment by electronicboy** [comment]
Because it's not an issue with hangar, your maven is running with java 11, as presented in the screenshot
