### ISSUE TITLE
Simplify navigation to the latest version

### ISSUE THREAD

**Issue by SlimeDog** [HangarMC/Hangar#1250]
### Is your feature request related to a problem?

It takes two clicks to get to the latest version of a plugin from the `Home` listing, in order to find out what changed:
- click 1: anywhere except the author link, navigates to the `Docs` tab
- click 2: something in `Pinned Versions`

(assuming the latest release is pinned -- otherwise three clicks)

### Describe the solution you'd like.

Link the `Last updated` text to the latest version.

### Describe alternatives you've considered.

Two (or three) clicks.

**Comment by MiniDigger** [comment]
not sure how I feel about the proposed solution, what do others think? 
its not really intuitive that way, and going from the project home page to the latest version (or the one you care about) is already pretty simple

**Comment by olijeffers0n** [comment]
Whilst I can see how clicking on the "last updated" would make sense to link the changelog, I don't really see this as much of an improvement. Also, to make it a noticeable link, i feel like you would need to underline and highlight the last updated in a different colour, which IMO would make the UI look worse

**Comment by SlimeDog** [comment]
Obviously, this isn't going to happen. It seems a shame to me, but I'm just a user.
