### ISSUE TITLE
Degraded performance and upload failure when projects reach >200 versions

### ISSUE THREAD

**Issue by WiIIiam278** [HangarMC/Hangar#1253]
### Observed/problematic behavior

I have a project on Hangar (https://hangar.papermc.io/William278/HuskHomes) with two channels; Alpha and Release.

I publish to the alpha channel continuously; every time a commit is made to my project, a version is published to Hangar via the API to this channel. This enables users to download bleeding edge versions if they so desire; only main releases are published to the release channel (in accordance with [TOS](https://hangar.papermc.io/guidelines#resource-updates))

I've now published [about 200](https://github.com/WiIIiam278/HuskHomes/compare/5bfe3816773e241f7d686d8234b90a819bcc767e...master) versions to Hangar, and have noticed degraded performance as I continue to publish more; specifically:
- Viewing the "versions" page on the site, I occasionally receive "request timed out after 4000ms" errors
- I can no longer upload additional versions; I receive a 500 Internal Server Error through the API. I suspect this is because the underlying logic to fetch the list of versions is timing out

### Expected behavior

Hangar gracefully handles me having more than 200 versions on a project, lets me continue to upload new versions, and smoothly browse existing ones

### Steps to reproduce

Have a project with over 200 versions, and attempt to upload another version, either through the API or the frontend.

You can also experience the timeout issue by going to https://hangar.papermc.io/William278/HuskHomes/versions and observing the errors in the bottom-right

**Comment by WiIIiam278** [comment]
> Opening the versions page doesn't seem to be slow (although it's not a paginator so lol). Just to clarify, when uploading via the website, did this happen when clicking 'create' in the final step, or before that?

Sorry for the slow reply! 

This occured both when hitting "Create" in the final page and when doing an upload via the API.

**Comment by kennytv** [comment]
This should be resolved with https://github.com/HangarMC/Hangar/commit/98733f665108e8783bd74b48b53f69ac5bb5973a
