### ISSUE TITLE
Versions get mixed up

### ISSUE THREAD

**Issue by N3liz** [HangarMC/Hangar#1259]
### Observed/problematic behavior

If you upload a version (for instance) plugin.jar and then delete it. After that upload another version with the same filename and artifact data but with a different file. Download the version you just uploaded. You will now have the old deleted version.

### Expected behavior

The file updating correctly.

### Steps to reproduce

1. Upload a file called plugin.jar, version 1.0.
2. Delete version 1.0.
3. Upload another file also called plugin.jar, version 1.0.
4. Download version 1.0.
Now you have the old file uploaded in step 1.

**Comment by kennytv** [comment]
Had a few attempts at fixing it and it works locally with minio, so not sure what's up with the actually used storage implementation. Will have to look into the actual s3 storage

**Comment by kennytv** [comment]
Alright the remaining issue was one of caching, should be fixed shortly.
