### ISSUE TITLE
Custom Accent Color

### ISSUE THREAD

**Issue by GamerCoder215** [HangarMC/Hangar#1263]
### Is your feature request related to a problem?

Currently, all of the buttons and accents on the Hangar are in blue. Similar to [BuiltByBit (or MC-Market)](https://builtbybit.com/), there are settings in Accounts that allow you to change this accent color.

### Describe the solution you'd like.

Allow players to specify their button accent color backgrounds and gradients in their accounts.

Personally, my favorite color is Green, so that's just a small comfort change that might be really nice. Plus, it might also be helpful for those who are colorblind.

### Describe alternatives you've considered.

You can (somewhat) achieve this with browser extensions modifying CSS, but it's a lot easier to set up if it is built-in.

**Comment by MiniDigger** [comment]
idk how i feel about it, but its also not the worst that happened to the design on the site, lol
![image](https://github.com/HangarMC/Hangar/assets/2185527/4fd7c538-92d9-4aff-af41-488e48c3fd61)

**Comment by GamerCoder215** [comment]
@MiniDigger there's a slight delay in the accent color loading. Is this linked to some other performance issue?

![2023-12-09 21-22-40](https://github-production-user-asset-6210df.s3.amazonaws.com/54124162/289335615-8a6c1ab4-a6cd-43dd-9b0c-e8b8b4d621ce.gif)

**Comment by MiniDigger** [comment]
It's only loaded once your browser loaded the JS, as the accent color is only saved locally. I didn't want to store it in the DB cause that's work.

**Comment by MiniDigger** [comment]
Thinking about it, maybe I should have just used a cookie, I'll take a look in a bit
