### ISSUE TITLE
Long name causes navbar to wrap to next line on mobile 

### ISSUE THREAD

**Issue by Badbird5907** [HangarMC/Hangar#1278]
### Observed/problematic behavior

![Screenshot_20231031_120036_Chrome](https://github.com/HangarMC/Hangar/assets/50347938/8dfd9919-f2c8-47e7-9ff5-b1e6042b427f)

### Expected behavior

The navbar should be in one line

### Steps to reproduce

1. Have a long name
2. Use a phone
Device info:
Samsung s21 5g g991w
Resolution: 1080px × 2400px
https://blisk.io/devices/details/galaxy-s21

**Comment by MiniDigger** [comment]
> The navbar should be in one line

I disagree, if there isn't enough space, what else should we do? I made it look slightly better tho
![https://i.imgur.com/LcE5iBL.gif](https://i.imgur.com/LcE5iBL.gif)
