### ISSUE TITLE
API/Hangar site gives download link that results in a 404 error

### ISSUE THREAD

**Issue by DaBlaze** [HangarMC/Hangar#1279]
### Observed/problematic behavior

After contacting the API for information about a version of a plugin, the downloadUrl is incorrect and results in a 404 error. This also seems to be an issue on the Hangar site as well when downloading plugin jar files.

### Expected behavior

The plugin jar file would be downloaded.

### Steps to reproduce

**Way one:**

1.  Ask the API for information regarding a plugin version using a request like this: 
    `https://hangar.papermc.io/api/v1/projects/viaversion/versions/4.8.1`
2. In the returned JSON, get the download link from: downloads > PAPER > downloadUrl
![Screenshot 2023-10-31 at 15-53-38 API Docs Hangar](https://github.com/HangarMC/Hangar/assets/7017951/eb2a84dc-9702-4e50-96a0-9853c3fc504e)
3. Try to download the plugin jar file with the downloadUrl.
4. The 404 arises when trying to download from the downloadUrl link given.
![Screenshot 2023-10-31 155649](https://github.com/HangarMC/Hangar/assets/7017951/350a0c93-4b8b-495c-a278-6154cdc41e5a)

**Way Two:**

1. Find plugin on Hangar site
2. Attempt to download plugin jar file
3. 404 error

### Other

The issue arises from the capitalization not being exact on the plugin name portion of the link.

Correctly Formatted Download Link:
    `https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/4.8.1/PAPER/ViaVersion-4.8.1.jar`

Incorrectly Formatted Download Link Given by API:
    `https://hangarcdn.papermc.io/plugins/ViaVersion/viaversion/versions/4.8.1/PAPER/ViaVersion-4.8.1.jar`

This issue seems to happen randomly as sometimes the API responds with the correct download link but other times will give a wrongly formatted one. The only thing I can think of is the API passing the lowercase plugin slug directly into the link rather than the properly capitalized plugin name? Or maybe the plugin name is incorrectly being lowercased at some point?

**Comment by MiniDigger** [comment]
its not consistent because stuff is cached, but I think I found the cause
