### ISSUE TITLE
Allow me to right click plugins "Open in new tab"

### ISSUE THREAD

**Issue by BleesTFE** [HangarMC/Hangar#1283]
### Is your feature request related to a problem?

Viewing the plugins, it's not possible to middleclick to open in a new tab.

### Describe the solution you'd like.

Idk, something to do with html or css. Opening items from a list in the same tab is so 2018

### Describe alternatives you've considered.

None

**Comment by Chris6ix** [comment]
This is basically #1276, so can be merged into one. I have adjusted my issue to include middle click.

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/Hangar/commit/3f3022f2fe46ac80e6b68eb0fe7d8d623fbe8ca2
