### ISSUE TITLE
Login with Microsoft doesnt allow switching account

### ISSUE THREAD

**Issue by 456dev** [HangarMC/Hangar#1300]
### Observed/problematic behavior

the login with microsoft prompt doesnt allow switching accounts: going back / clicking cancel returns to paper and shows an error

### Expected behavior

the ability to return to the account chooser screen

### Steps to reproduce

log out of all but 1 microsoft account
in hangar, try signing in
once you get to microsoft, try to choose a different account than the one it prompts you for

### Other

the prompt parameter should fix it
https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#send-the-sign-in-request

**Comment by 456dev** [comment]
findmcserver, which recently had the same issue, uses prompt=login, which asks to verify credentials (password / mobile prompt / whatever) each login, but has a button to switch accounts

**Comment by MiniDigger** [comment]
cant repro? 
![image](https://github.com/HangarMC/Hangar/assets/2185527/707295fb-f282-469c-8ef0-d2e1b88788a6)
