### ISSUE TITLE
Unknown error - bf() is undefined

### ISSUE THREAD

**Issue by Justman100** [HangarMC/Hangar#1302]
### Observed/problematic behavior

![grafik](https://github.com/HangarMC/Hangar/assets/149507651/4c50946a-9567-4d83-bd56-ab2f6bdc3b6a)

### Expected behavior

![grafik](https://github.com/HangarMC/Hangar/assets/149507651/4e3c0416-ab3f-4d79-bd81-5512e18e1b20)

### Steps to reproduce

Follow [Development Setup in README.md](/HangarMC/Hangar#development-setup)

**Comment by Justman100** [comment]
@MiniDigger

What do?

**Comment by Justman100** [comment]
@MiniDigger

Please help...

**Comment by MiniDigger** [comment]
please dont spam...
if you need help with contributing to hangar, please join our discord and provide detailed info about what you did and the exact error and full logs.
https://discord.gg/zvrAEbvJ4a
