### ISSUE TITLE
Invalid documentation for endpoint `users/{user}/watching

### ISSUE THREAD

**Issue by Dawsson** [HangarMC/Hangar#1306]
### Observed/problematic behavior

the dropdown menu provides sorting methods which are not supported by hangar.

### Expected behavior

correct sorting values

### Steps to reproduce

![image](https://github.com/HangarMC/Hangar/assets/88049488/21191672-d321-45b1-a995-5d6acf8549a7)
![image](https://github.com/HangarMC/Hangar/assets/88049488/9cc6e0e0-3faa-44dd-8866-77b4eddf80a8)

### Other

User endpoint code: https://github.com/HangarMC/Hangar/blob/staging/backend/src/main/java/io/papermc/hangar/controller/api/v1/UsersController.java

**Comment by Dawsson** [comment]
You cannot use any sorting method, I assume this is because these do not have the `ApplicableSorters` annotation

**Comment by MiniDigger** [comment]
> potential swagger issue found, sort param but no @ApplicableSorters annotation?: getUserWatching
> potential swagger issue found, sort param but no @ApplicableSorters annotation?: showStarred

**Comment by MiniDigger** [comment]
decided to just add the sorters, clearly they were meant to be sortable
