### ISSUE TITLE
User watching/starred has pagination, pinned does not.

### ISSUE THREAD

**Issue by Dawsson** [HangarMC/Hangar#1307]
### Observed/problematic behavior

Pinned does not contain pagination

### Expected behavior

Pinned contains pagination

### Steps to reproduce

https://hangar.papermc.io/api/v1/users/Dawson/watching?limit=10&offset=0
https://hangar.papermc.io/api/v1/users/Dawson/pinned?limit=10&offset=0

View the pagination missing for the pinned endpoint

### Other

Not a bug
```java
    @Override
    public ResponseEntity<List<ProjectCompact>> getUserPinnedProjects(final String userName) {
        return ResponseEntity.ok(this.usersApiService.getUserPinned(userName));
    }
```

**Comment by kennytv** [comment]
You can only pin a handful of things, pagination here would be unnecessary
