### ISSUE TITLE
Duplicate parameter sort for /api/v1/users/{user}/watching in openapi spec

### ISSUE THREAD

**Issue by JulianVennen** [HangarMC/Hangar#1313]
### Observed/problematic behavior

The [openapi spec](https://hangar.papermc.io/v3/api-docs.yaml) contains the following parameters for the /api/v1/users/{user}/starred and /api/v1/users/{user}/watching endpoints:
```yaml
      - name: sort
        in: query
        description: How to sort the projects
        required: false
        schema:
          $ref: '#/components/schemas/ProjectSortingStrategy'
# ...
      - name: sort
        in: query
        description: Used to sort the result
        style: form
        schema:
          type: string
          enum:
          - name
          - createdAt
          - projectCount
          - locked
          - org
          - roles
```

### Expected behavior

The same parameter name should not appear twice

### Steps to reproduce

Open the openapi spec and search for /api/v1/users/{user}/watching, then scroll to the parameters

**Comment by MiniDigger** [comment]
seems like this was fixed at some point
