### ISSUE TITLE
Invalid MC version for a platform specified

### ISSUE THREAD

**Issue by lewmilburn** [HangarMC/Hangar#1314]
### Observed/problematic behavior

When uploading a new plugin the "Invalid MC version for a platform specified" error would appear alongside a number of errors in the console.

![image](https://github.com/HangarMC/Hangar/assets/63267144/4ddf5fcf-82c5-444e-86b4-b0ab5c611b68)
![image](https://cdn.discordapp.com/attachments/1098348646757568541/1197160811429363863/image.png?ex=65ba41e3&is=65a7cce3&hm=af486b30e1ab817ecb5f5e81fa7bd8b279640b3a9aead77c78b6fe1effcea27a&)
![image](https://github.com/HangarMC/Hangar/assets/63267144/a0cfa2d6-1a62-4cd5-8d10-ce2ecf330908)

### Expected behavior

- The plugin would upload.

### Steps to reproduce

1. Create new project
2. Upload new file

### Other

https://hangar.papermc.io/LewMC/Essence

**Comment by kennytv** [comment]
Sorry for missing the Discord messages; should be fixed in about 10 minutes once prod restarted

**Comment by lewmilburn** [comment]
It's ok! I wasn't sure if I put it in the right place on discord so thought I'd pop it here and the devs would see it - thank you for fixing! 😄
