### ISSUE TITLE
Hangar asking for 2FA with no further information.

### ISSUE THREAD

**Issue by lewmilburn** [HangarMC/Hangar#1317]
### Observed/problematic behavior

Hangar is asking for 2FA input. No emails are sent nor is there any option to input a code or anything.
![image](https://github.com/HangarMC/Hangar/assets/63267144/16f9c26a-550e-420d-a283-ebe902d5a84a)

### Expected behavior

?

### Steps to reproduce

Login to Hangar account.

**Comment by MiniDigger** [comment]
That's uhmm, interesting, what's your username?

**Comment by lewmilburn** [comment]
Hi, it's LewMC. Thanks :)

**Comment by MiniDigger** [comment]
thanks, managed to repo, requires an account with no 2fa but oauth and password

**Comment by lewmilburn** [comment]
Awesome thank you! Is working for me now :)
