### ISSUE TITLE
Code blocks with long text aren't cut off, causing them to go beyond max-width of text area

### ISSUE THREAD

**Issue by Andre601** [HangarMC/Hangar#1326]
### Observed/problematic behavior

Code blocks with long text that go beyond the max width of a text area don't seem to get cut of, or have other measures in place like word-wrap or similar.

This causes them to just go beyond the max width of the text area, resulting in everything, especially the sidebar, being pushed over.

Screenshot:
![image](https://github.com/HangarMC/Hangar/assets/11576465/ce30dc13-2777-4792-bca9-6348a7c576cd)

### Expected behavior

Code blocks should stay within the textarea's max width and either split to new lines or have scrollable content if going beyond it.

### Steps to reproduce

I cannot say if this happens on all text areas or just within releases, so I give steps on release.

1. Create a new release
2. On the text field for the description, add a code block that has text going beyond the max width of the text area.
3. Save release
4. Observe

**Comment by MiniDigger** [comment]
I guess this was fixed at some point, can't repro on this page https://hangar.papermc.io/Andre_601/AdvancedServerList/versions/4.0.0

**Comment by Andre601** [comment]
Still can.
![grafik](https://github.com/HangarMC/Hangar/assets/11576465/3b5e1d04-2665-4f71-af14-6987e78ff93a)

**Comment by MiniDigger** [comment]
can repro in firefox
