### ISSUE TITLE
Management tab for projects by organizations is always empty

### ISSUE THREAD

**Issue by NonSwag** [HangarMC/Hangar#1328]
### Observed/problematic behavior

I had a typo within my project name and wanted to rename/delete it, but the management tab under the projects settings is empty
![image](https://github.com/HangarMC/Hangar/assets/54660361/e322d2e6-6591-4383-bd64-341397f2a590)

### Expected behavior

Ability to rename transfer and delete the project
![image](https://github.com/HangarMC/Hangar/assets/54660361/65f5603f-693f-4d04-842a-6aa2d7ecf621)

### Steps to reproduce

create a new project for an organization and head to settings/management

### Other

I already tried to make myself admin, but it does not change anything

**Comment by kennytv** [comment]
Do you see any errors in the console when you press F12? And what's the project name?

**Comment by NonSwag** [comment]
The project name is VanillaMSGs (not visible)
![image](https://github.com/HangarMC/Hangar/assets/54660361/b3639323-1263-4e63-a511-944647e8b27c)
The console only spits out warnings, no errors (log-level info is filtered in the screenshot)

**Comment by NonSwag** [comment]
![image](https://github.com/HangarMC/Hangar/assets/54660361/6acde906-b590-4ffe-8e93-ec0e34b404b1)
the corresponding div only persists out of comments

**Comment by NonSwag** [comment]
any update ?

**Comment by NonSwag** [comment]
this issue still persists. somebody looked into it yet?

**Comment by MiniDigger** [comment]
I can't repro this. after the next prod deployment, please login, navigate to that settings page and enter `hangarDebug.debugPerms()` in the javascript console and send a screenshot of the output.
it should look something like this:
![image](https://github.com/HangarMC/Hangar/assets/2185527/b44e0e5f-2d70-4448-8d8e-0a2a0d0c1d5e)

**Comment by MiniDigger** [comment]
![image](https://github.com/HangarMC/Hangar/assets/2185527/60e573ab-9762-497b-b1ec-7fe84d4b0e3a)

**Comment by MiniDigger** [comment]
![image](https://github.com/HangarMC/Hangar/assets/2185527/6e06e03d-64a1-4921-b898-4efb22d6e295)
