### ISSUE TITLE
Case sensitivity is not consistent throughout API

### ISSUE THREAD

**Issue by dxbednarczyk** [HangarMC/Hangar#1331]
### Observed/problematic behavior

Requesting info about plugins, for example to get the latest release of [Chunky](https://hangar.papermc.io/pop4959/Chunky), hitting 
`/api/v1/projects/chunky/latestrelease` 
returns an OK result if the slug of the project is all lowercase.

However, `/api/v1/projects/chunky/versions/1.3.92/PAPER/download` returns a 404.
This endpoint requires the slug for the project to be properly capitalized, in this case as `Chunky`.

### Expected behavior

The endpoints should have the same case sensitivity, or specify what they require

### Steps to reproduce

Different endpoints have different capitalization requirements. I found that messing around with the request builders on the [API docs](https://hangar.papermc.io/api-docs) were a good tool to see which endpoints were case-sensitive or not.

The two URLs I used that raised this issue:
https://hangar.papermc.io/api/v1/projects/chunky/latestrelease
https://hangar.papermc.io/api/v1/projects/chunky/versions/1.3.92/PAPER/download

**Comment by MiniDigger** [comment]
latest release seems to work fine for me, i.e https://hangar.papermc.io/api/v1/projects/chUnky/latestrelease returns fine, the download ill have to take a look at. they just redirect to our cdn (which cant handle casing), they most likely just pass the user data and not the db data.

**Comment by MiniDigger** [comment]
thanks, if you find any other, please lemme know and ill try to get to these faster...
