### ISSUE TITLE
Dependency Card Improvements

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#1334]
there seem to be multiple bugs:
* editing/saving isnt possible, the button is always grayed out
* velocity dependencies seem to be broken completely (they arent displayed)? 
* clicking links in the box leads to nothing

**Comment by Andre601** [comment]
Regarding 2, for me it also happens on waterfall.

My assumption is, that the frontent (probably) is skipping the dependency, if it wss defined in a previous platform.

I.e. adding KennyTV's Maintenance to all platforms of a release only displays it for Paper, not for Waterfall amd velocity.

**Comment by MiniDigger** [comment]
this was quite the pain to fix, but should be good now hopefully. it completely broke when we made slugs unique.
