### ISSUE TITLE
Add Ownership Transfer

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#134]
Ownership transfers for Projects/Organizations
Organization Owner and Project Owners should be able to transfer ownership to another user.

**Comment by AwesomeDude091** [comment]
I could try this...

**Comment by kennytv** [comment]
Things to make sure to have would be:
- Fat final confirmation and cancellation when not accepted yet
- The other end has to receive a request to accept first (has to work for both projects and users, else don't do moving to projects for now)
- Cooldowns

**Comment by AwesomeDude091** [comment]
I shall attempt :))

**Comment by kennytv** [comment]
Done with project to user transfer, organization to user transfer. Only missing project to organization transfer
