### ISSUE TITLE
Multiple Sidebars No Longer Supported

### ISSUE THREAD

**Issue by Pheotis** [HangarMC/Hangar#1342]
### Observed/problematic behavior

The page for our [project](https://sgrewritten.org/paper) was created quite a while ago, with multiple sidebars full of links.
Attempting to save after adding a new link to any sidebar produces fails with "Can only select each Type once".

### Expected behavior

Multiple sidebars have been supported since the beginning; it would be great if they continued to be supported.

### Steps to reproduce

1. Go [here](https://hangar.papermc.io/Stargate/Stargate/settings/links).
2. Try to add something to the links bar.
3. Try to save it
4. Observe the error.

**Comment by MiniDigger** [comment]
ah fun. #1211 caused me to add the validation to the frontend, since backend always had blocked multiple top sections (which makes sense). but the validation was overly aggressive in the frontend and now blocks all duplicated types
