### ISSUE TITLE
Unable to modify sponsors bar.

### ISSUE THREAD

**Issue by Pheotis** [HangarMC/Hangar#1343]
### Observed/problematic behavior

(Possibly related to #1342)
Attempting to edit the sponsors bar for [this project](https://sgrewritten.org/paper) fails with "Unable to save page".
Editing this bar is therefore impossile.

### Expected behavior

It should be possible to add content to the sponsors bar.

### Steps to reproduce

Go [here](https://sgrewritten.org/paper) and try to add something to the sponsors bar.
It will fail with that error.

**Comment by MiniDigger** [comment]
stumbled upon this myself rn and remember I had an unread notification about this new issue, lol.
one line fix
