### ISSUE TITLE
Improvements/changes to file storage

### ISSUE THREAD

**Issue by kennytv** [HangarMC/Hangar#135]
Improve file blob storage (IchBinJoe wanted to take a shot at working out a concept) and otherwise add file size limits and a limit of builds in a specific time window for normal users (?)

**Comment by MiniDigger** [comment]
DenWav wanted to use b2 for this

**Comment by MiniDigger** [comment]
absatract it out so that local can use files and remove can use block stroage

**Comment by MiniDigger** [comment]
TODO:
* use CDN for download api (prolly just redirect to cdn?)
* use CDN for images (maybe auth can handle this?)
* use blob storage for auth images
* reimplement multiple platform downloads (link stuff)
