### ISSUE TITLE
Markdown Alerts

### ISSUE THREAD

**Issue by NonSwag** [HangarMC/Hangar#1350]
### Is your feature request related to a problem?

GitHub has some amazing [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) that I would like to use on Hangar as well

### Describe the solution you'd like.

Adapt the same syntax, so markdown files from GitHub work on Hangar

### Describe alternatives you've considered.

-

### Other

> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

**Comment by MiniDigger** [comment]
![image](https://github.com/HangarMC/Hangar/assets/2185527/c07e0e9d-0a5a-4a2e-bec2-37168abc3869)

**Comment by NonSwag** [comment]
You are crazy
thanks for adding this so quick
I'm going to close this issue
