### ISSUE TITLE
Connections throttled

### ISSUE THREAD

**Issue by SlimeDog** [HangarMC/Hangar#1354]
### Observed/problematic behavior

Since a few days ago, it appears that my connections are throttled. Downloads are taking more than twice as long as previously.

### Expected behavior

I run update check on Paper, Velocity, and plugins every 15 minutes. I do not believe that I am not abusing the service. Connections should not be throttled. I would be happy to modify my timings if that would resolve the issue.

### Steps to reproduce

Observation of download speeds.

### Other

Masked IPv6: 2601:BBBB:CCCC:DDDD:EEEE:FFFF:ce6f:4b7b
Masked IPv4: XXX.YYY.142.28

**Comment by MiniDigger** [comment]
we dont have any code to throttle stuff. all downloads are handled by cloudflare, and I am not aware of them doing any throtteling either, if they think you are abusing stuff they will just block you.
cloudflare doesn't let me look up traffic by partial IPs, can you provide the full IPs (my discord DMs are open, `minidigger`) or the user agent or some cf ray ids? then I could look f the cloudflare dashboard says anything.

and just to understand, you are checking for a new version every 15 min and if a new one has been found, you automatically download it? thats fine, as long as you don't actually download every 15 min when nothing changed, lol

**Comment by SlimeDog** [comment]
My update-check runs every 15 minutes. I do no automatic downloads. When I notice an update on my dashboard (not necessarily immediately -- I sleep sometimes), I initiate a download manually. If I initiate a download from my desktop (a link on my dashboard), it is throttled, which did not used to be the case. If I initiate a download from one of my servers (a different IP block) the download is instantaneous.

**Comment by SlimeDog** [comment]
IP address sent to Discord DM.

**Comment by MiniDigger** [comment]
investigated a few requests and there were all cf cache hits, so nothing we can do at our end

**Comment by SlimeDog** [comment]
Thanks for investigating. It's probably just upstream network misconfiguration. They'll sort it eventually.
