### ISSUE TITLE
WebP images cannot be uploaded for projects

### ISSUE THREAD

**Issue by TheMeinerLP** [HangarMC/Hangar#1361]
### Observed/problematic behavior

When uploading an image in WebP format, the format is rejected in the project settings.

### Expected behavior

It should be possible to upload WebP images.

### Steps to reproduce

1. create a project
2. go to the project settings 
3. select an icon in the WebP or try it out

### Other

There is no explicit error message Apple does not generally allow you to select the file format

**Comment by MiniDigger** [comment]
> Apple does not generally allow you to select the file format
apple being apple I guess, why offer choice
