### ISSUE TITLE
Non-language options

### ISSUE THREAD

**Issue by PetarMc1** [HangarMC/Hangar#1362]
### Observed/problematic behavior

In the Languages, there are two non-language options
![image](https://github.com/HangarMC/Hangar/assets/160483025/48c57a1d-0050-4c20-a141-3d6514291751)

### Expected behavior

The two non-language options should not be there.

### Steps to reproduce

Go to Settings 
Go to other
Open languages menu

**Comment by MiniDigger** [comment]
The in context editor is supposed to be there, the broken once idk

**Comment by MiniDigger** [comment]
we now skip broken files
