### ISSUE TITLE
Wrong title/name

### ISSUE THREAD

**Issue by PetarMc1** [HangarMC/Hangar#1363]
### Observed/problematic behavior

The name of the languages options in the settings is wrong
![image](https://github.com/HangarMC/Hangar/assets/160483025/4f30a986-0c30-4b4e-ba43-b6504084a917)

### Expected behavior

It should say something like 'Languages"

### Steps to reproduce

Go to Settings
Go to Other

**Comment by Leguan16** [comment]
see #1358
