### ISSUE TITLE
Can't change language after in-context translation

### ISSUE THREAD

**Issue by Mathildeuh** [HangarMC/Hangar#1366]
### Observed/problematic behavior

Can't change lang after select in-context translation, i'm always redirected to crowdin can't access to hangar

### Expected behavior

Change that

### Steps to reproduce

Go to your language settings et putt "in-context translation" and refresh the page, you are now not able to access paper hangar anymore

**Comment by Mathildeuh** [comment]
https://youtu.be/2WKSYmaTgWI

**Comment by Mathildeuh** [comment]
So i can't maintain my plugins

**Comment by kennytv** [comment]
I reset your language to English

**Comment by Mathildeuh** [comment]
Thanks i see <3
