### ISSUE TITLE
"back" arrow in the resource page 

### ISSUE THREAD

**Issue by TymekSL** [HangarMC/Hangar#1368]
### Is your feature request related to a problem?

PLease add button for back to the main page. Example i saw plugin viaversion, and i want continue search but i can't back to the example page 5. I need click home button and then scroll down and move to the 5 page, its hard 
so pls add button for previous page 

### Describe the solution you'd like.

^ 

### Describe alternatives you've considered.

arrow button

**Comment by MiniDigger** [comment]
![https://i.imgur.com/1eDMpHh.gif](https://i.imgur.com/1eDMpHh.gif)
