### ISSUE TITLE
API Endpoint to recognize plugin jar via hash

### ISSUE THREAD

**Issue by Dawsson** [HangarMC/Hangar#1369]
### Is your feature request related to a problem?

No, I want it to be added to recognize a plugin by its hash. I would like to find a source of where a plugin has come from inside my plugin package manager. 

### Describe the solution you'd like.

I would like an endpoint which requires a hash, then provides what plugin and version it has come from. See this in action via the Modrinth API: https://docs.modrinth.com/#tag/version-files

### Describe alternatives you've considered.

Scrape through every single available plugin, and every released version under every released channel, get the hash of said plugin, store inside my of own database (semi illegally), then create an API which would create said endpoint and aggregate a result for the user.

I have hypothetically created this in the past, and it was allegedly not a fun experience.

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/Hangar/commit/060d99b60fe60a8a33fe958496b5715db2f092f8
