### ISSUE TITLE
Website social prefixing `https://`

### ISSUE THREAD

**Issue by srnyx** [HangarMC/Hangar#1370]
### Observed/problematic behavior

When I set my website under Socials in Settings, it requires me to put `https://srnyx.com` rather than just `srnyx.com`
Then, when I go to my profile and click on the website button, it takes me to `https://https://srnyx.com`

### Expected behavior

[1] The website field in settings shouldn't require `https://`, [2] the website button shouldn't prefix `https://`, or [3] it should be dynamic (if it doesn't have a protocol, add one, if it already has one, do nothing)

I think either 2 or 3 should be done, as since it's been requiring `https://` this entire time, it would break everyone's current websites if 1 is done

### Steps to reproduce

1. Add a website to your profile (it'll make you put `https://`)
2. Click the button (it'll take you to `https://https://website.com`)

**Comment by MiniDigger** [comment]
prod DB has been adjusted
