### ISSUE TITLE
Alternative sorting for project versions page

### ISSUE THREAD

**Issue by FlorianMichael** [HangarMC/Hangar#1383]
### Is your feature request related to a problem?

My project https://hangar.papermc.io/ViaVersion/ViaRewind auto publishes to hangar in the following schematic:
- releases go to the "Release" label
- snapshots go to the "Snapshot" label
- commits on the dev branch to the "Alpha" label

Since every commit is published, it doesn't take long for only snapshot/alpha versions to be visible on the page. Users then download a snapshot or alpha version since they don't immediately see the release and error occur since alpha/snapshot versions usually also require snapshot versions from my upstream dependencies ViaVersion and ViaBackwards.

### Describe the solution you'd like.

A solution would be to allow the project author to change the default values for the channel/version type selection:
<img width="342" alt="image" src="https://github.com/user-attachments/assets/a88317f7-e017-4b15-86d1-503d07c1791f">

To be fair my case is more specific, but I could also imagine this to be useful for other projects as well. This way people can publish dev builds but offering the user releases to prevent automatically using dev builds and running into issues.

### Describe alternatives you've considered.

As alternatives (or second feature) it would be cool to have a mode were:
- only the latest version of every Release channel is displayed.
- you can pin versions which are displayed above unpinned versions.

**Comment by MiniDigger** [comment]
this is already a thing :)
![image](https://github.com/user-attachments/assets/d31c59f8-cb3e-439c-8ad8-8bf128774cdf)
![image](https://github.com/user-attachments/assets/e6914516-bf59-4e42-8c2c-961395c1ffa5)

**Comment by FlorianMichael** [comment]
Oh I should have looked at that menu, thank you
