### ISSUE TITLE
Can't verify gmail

### ISSUE THREAD

**Issue by alexleo5** [HangarMC/Hangar#1411]
### Observed/problematic behavior

the verify email never sends and I check EVERY INC OF MY GMAIL THIS DOES INCLUDE THE SPAM FOLDER 

### Expected behavior

The verify code

### Steps to reproduce

None

### Other

Fix it please

**Comment by MiniDigger** [comment]
please email core@papermc.io with your hangar username and the email you used to sign up, I can't help you without any info.
