### ISSUE TITLE
Sanitize project, org and user names

### ISSUE THREAD

**Issue by notOM3GA** [HangarMC/Hangar#220]
I was told to make this issue on discord by MiniDigger.

Context was I created a project with a `.` in the name and it gives me a 404 when i access it.

EDIT (by MM)
A list of things that need to be checked
- [ ] project names
- [ ] user names (but that should be one on HangarAuth)
- [ ] organization names
- [ ] version names
- [ ] project page names

pretty sure that's it.

**Comment by Machine-Maker** [comment]
Ok, usernames are now taken care of. Valid characters are `a-zA-Z0-9_-`.
