### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#275]
Finish setting up the CSP header. Initial work is done in [ContentSecurityPolicyFilter](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/filters/ContentSecurityPolicyFilter.java) and [HangarController](https://github.com/PaperMC/Hangar/blob/master/src/main/java/io/papermc/hangar/controller/HangarController.java#L75)

Still blocking a few requests I think. And there are probably more than a few <script> tags that need the nonce added to them.

**Comment by MiniDigger** [comment]
set to report only for now, vue-i18n uses eval for some fucking reason, gotta fix that

**Comment by MiniDigger** [comment]
this is done
