### ISSUE TITLE
Logo for Hangar

### ISSUE THREAD

**Issue by mdcfe** [HangarMC/Hangar#315]
We should design a logo for Hangar to replace the temporary logo.

Below are a few mockups I came up with (after some discussion in Discord):

![image](https://user-images.githubusercontent.com/1917406/105405096-a9106700-5c22-11eb-9d89-ad43f9f6e1b2.png)

The orange colour is sampled from the squares in the background of the PaperMC organisation logo, and future projects could use a similar design sampling another colour.

**Comment by Machine-Maker** [comment]
@Sil3ntWxlf has mentioned that he is interested in working on the logo as well.

**Comment by Sil3ntWxlf** [comment]
Heyo, I have a few artists that I could take to in order to get us a new logo. I like the concept of an actual hangar but I feel like the colours of the projects should either be changed or removed completely. Personally, I am a fan of a sleek and simplistic design however if its preferred to look more so like the paper logo, than we can accommodate.

**Comment by electronicboy** [comment]
I think that the biggest concept is a level of consistency, awe inspiring logos are nice, but, I believe that brand consistency is as much of an importance, especially in gaining trust, we don't want hangar to look like some off-branded solution type deals

**Comment by Chew** [comment]
If we're going with the whole "each project is a color" logic. Arguably the logo should be a (slightly rotated) colored square, at least the outline. The logic behind each paper in the stack is a project should fit because, as these are shown, it's just the same stack, but they're all the same color.

**Comment by Sil3ntWxlf** [comment]
Yeah I agree with consistency however in my opinion, Hangar is not paper thus I feel like it should stand out in its own way but also be relatively similar. For example, a more modern, simplistic design with elements of what paper has in its logo such as the paper plane or what not. I'll make a mockup to show what I mean.

**Comment by Sil3ntWxlf** [comment]
How would something like this fare?
![hangar-mockup_1 1 0](https://user-images.githubusercontent.com/40921343/105434892-377bed00-5c11-11eb-8eaa-20726d32dbd6.png)

**Comment by mdcfe** [comment]
@Chew 
> Arguably the logo should be a (slightly rotated) colored square, at least the outline. The logic behind each paper in the stack is a project should fit because, as these are shown, it's just the same stack, but they're all the same color.

If we were going to do this, I feel it would work best to change the shades of the colours slightly to make sure the square stands out from both white and dark backgrounds and the hangar icon on top. I'd also be a bit wary of having other projects' logos all at different angles, as they're not all common/natural angles for icons. Could maybe have them all at the same angle?

@Sil3ntWxlf My main concern with this logo is that it's quite busy and the detail would make it unrecognisable at lower resolutions. For example, as a 16x16 favicon:

![image](https://user-images.githubusercontent.com/1917406/105469420-1c03f700-5c90-11eb-8825-48a509a49bdf.png)

Of course it would be rendered properly, not quickly downsized, but it's still a bit crowded. In contrast, the logos I suggested above are a bit easier on the eyes when downsized:

![one-three](https://user-images.githubusercontent.com/1917406/105470042-fc210300-5c90-11eb-982f-eaf03e904255.png) ![one-three copy 2](https://user-images.githubusercontent.com/1917406/105470043-fc210300-5c90-11eb-8d3a-6e062f9c3dd4.png) ![one-three copy](https://user-images.githubusercontent.com/1917406/105470040-fb886c80-5c90-11eb-951f-c6161b646997.png) ![image](https://user-images.githubusercontent.com/1917406/105470244-3a1e2700-5c91-11eb-817b-edec85a56c20.png)

It also feels a bit awkward shoehorning the plane into the logo, especially as the plane icon is more detailed than the hangar. If we want to allude to the PaperMC brand, I'd prefer used the squares, either just with the grey background like in your first concept, or with something like mine or Chew's suggestions which use the colour squares.

**Comment by Sil3ntWxlf** [comment]
I see what you mean there! It is a bit hard to make out. I'll have go back to the drawing boards for a potential candidate
.

**Comment by kadenscott** [comment]
If I can throw my 2c here, I do like md's idea of each Paper thing having it's own colour. I think that would make things recognizable and easy to understand (i.e. "Oh, orange? yep, that's Hangar")

**Comment by Sil3ntWxlf** [comment]
That's quite fair. I'll continue to add mock-ups based off of the suggestions as well so we can all agree on a final product at some point.

**Comment by aurorasmiles** [comment]
> 
> 
> If I can throw my 2c here, I do like md's idea of each Paper thing having it's own colour. I think that would make things recognizable and easy to understand (i.e. "Oh, orange? yep, that's Hangar")

I also like that idea the most. Hangar would be orange, Paper would be some other color and the PaperMC organisation would have all the colors.

**Comment by mdcfe** [comment]
Just for comparison, I traced @Sil3ntWxlf's hangar shape and placed it on top of the squares: ![one-three silent](https://user-images.githubusercontent.com/1917406/105522855-a6bb1500-5cd5-11eb-9e38-e7968004264c.png)
![one-three-silent-full](https://user-images.githubusercontent.com/1917406/105523035-d79b4a00-5cd5-11eb-98ba-e9c06a368101.png)

I like this one, even if IMO it looks a bit less like a hangar than the others.

**Comment by Machine-Maker** [comment]
Yes, I think that is the best-looking hangar shape so far.

**Comment by DemonWav** [comment]
The favicon would just be the hangar shape itself without the rest, shrinking that whole logo into favicon size would not be a good idea.

**Comment by MiniDigger** [comment]
Mmh, just the hangar shape feels kinda boring, if you look at the small icons in here https://github.com/PaperMC/Hangar/issues/315#issuecomment-765254428 i wouldn't say it looks bad when at favicon size (especially since most browsers accept high res icons now too)

**Comment by jamierocks** [comment]
Excuse the crudeness of this (I threw it together in a couple of minutes), but maybe a logo where the paper plane is flying away from the hangar could work?

![Untitled](https://user-images.githubusercontent.com/5103549/105552320-a766a200-5cfb-11eb-88d7-b095b0f8e3c0.png)

**Comment by Machine-Maker** [comment]
hmm, I do like that idea (with a better looking hangar obv)

**Comment by jamierocks** [comment]
> 
> 
> hmm, I do like that idea (with a better looking hangar obv)

Naturally, its a shitty trace of the Paper logo for speed too :)

**Comment by aurorasmiles** [comment]
I don't really like the idea from jamierocks, it looks out of place & really weird for me

**Comment by DemonWav** [comment]
Yeah @MiniDigger makes a good point about high rest favicons.

**Comment by Astrashh** [comment]
A couple design propositions

###### Design 1

Based on the idea of two sheets of paper, forming a lowercase h. The arch on the back sheet of paper also somewhat resembles the arched shape of an aircraft hangar. The text here is mostly used for presentation purposes.

![image](https://user-images.githubusercontent.com/73215501/114658962-0bff2f00-9d36-11eb-8b9e-ded95a763d63.png)

![image](https://user-images.githubusercontent.com/73215501/114659306-b5462500-9d36-11eb-9044-0ab758500eb1.png)

###### Design 2

The shape of this logo is again inspired by aircraft carrier, however I think the shape gets lost with the stem of the `h`. Between the two I think this is the weaker design.

![image](https://user-images.githubusercontent.com/73215501/114659332-c2631400-9d36-11eb-9982-e4176bbb887b.png)

![image](https://user-images.githubusercontent.com/73215501/114659493-0fdf8100-9d37-11eb-9dda-00c7440c0101.png)

**Comment by DemonWav** [comment]
Big fan of design 1. I think that looks sick.

**Comment by YTMrSnipa** [comment]
I love both the designs, they look equally good, though the first one looks more fancy 
Maybe you can have a dark theme on hangar, and you can use both the logos there

**Comment by Machine-Maker** [comment]
As I mentioned in the discord, I too prefer design 1. As for the font, should it be the same as PaperMC? Or should it have its own?

**Comment by DenWav** [comment]
We decided since it was posted that we would use the first design proposed by @Astrashh. Thanks!

**Comment by DenWav** [comment]
@Astrashh if you're still around and could post or PR the SVG for the logo, we would really appreciate that.

**Comment by Machine-Maker** [comment]
https://gist.github.com/Astrashh/e162b443bf522726153af73a4ad9946f
for future reference
