### ISSUE TITLE
In Project/Version lists, distinguish between visibilities

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#415]
When looking at a project list, the projects shown may vary because some are hidden and you might have permissions to see them. There should be an at-a-glance way to distinguish those projects/versions.

The `Visibility` enum already has a field for css classes, but they are as-of-yet, unused in the frontend.

**Comment by kennytv** [comment]
Fixed with https://github.com/HangarMC/Hangar/commit/4b77ae63781dde0a080438e87f5e5405e682eca3
