### ISSUE TITLE
Illegal user, project, version names

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#456]
There is a set of illegal user, project, and version names based on routing that need to be figured out. It's kind of a pain to go through and check all api, frontend routes to see if a project version named `settings` or something like that will cause issues.

**Comment by MiniDigger** [comment]
We have a separste issue to sanitize that kind stuff, prolly should be combined in a central place

**Comment by Machine-Maker** [comment]
Oh I guess #220 is similar, but it doesnt talk about conflicting routes, just having illegal characters, this issue is more towards conflicting routes, rather than illegal characters. (although they are similar)

**Comment by Machine-Maker** [comment]
### Illegal Usernames
- api
- authors
- linkout
- logged-out
- new
- notifications
- staff
- admin
- organizations
- tools

**Comment by Machine-Maker** [comment]
### Illegal Version Names
* recommended
