### ISSUE TITLE
handle plugin.yml for paper and waterfall

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#458]
Both paper and waterfall support the `plugin.yml` as their "configuration" file, and as far as I know, there isn't a way of determining which it's for, so this might have to be a "manual" thing, where after uploading a file, there's a button "convert to waterfall" if only a plugin.yml is detected. Open suggestions on how to handle this for sure tho, cause I'd like it to be automatic.

**Comment by MiniDigger** [comment]
its now possible to change the platform manually
