### ISSUE TITLE
Wrong icon in menu

### ISSUE THREAD

**Issue by mindstormjak** [HangarMC/Hangar#535]
In the frontend menu when hovering with the cursor on the PaperMC logo here in https://hangar.benndorf.dev/ the icon for Hangar is a house, as shown down below

![image](https://user-images.githubusercontent.com/69505539/124469289-75716580-dd9a-11eb-8eae-8a4feb5c9f86.png)

But here in https://hangar-auth.benndorf.dev/accounts/register/ the icon for Hangar is an electrical plug

![image](https://user-images.githubusercontent.com/69505539/124469786-13fdc680-dd9b-11eb-939e-3f7989340aa1.png)

It should be an easy fix by changing the class of the icon element

**Comment by MiniDigger** [comment]
this is no longer an issue with the new auth site
