### ISSUE TITLE
Allow external wikis

### ISSUE THREAD

**Issue by NoahvdAa** [HangarMC/Hangar#549]
Allow users to add an external wiki page to their plugin.

**Comment by NoahvdAa** [comment]
I feel like allowing external links should definitely be an option as
people will just put the links in the description instead.

**Comment by lokka30** [comment]
If the user experience by embedding the wiki thru either API is akin to using it on the actual sites, then I'm all for going with MiniDigger's idea. Though, if it isn't difficult, being able to replace it with a link would solve both ideas.
