### ISSUE TITLE
implement homepage search order dropdown

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#568]
need to use our sorters systems

![https://i.imgur.com/v2JJWGc.png](https://i.imgur.com/v2JJWGc.png)

**Comment by AwesomeDude091** [comment]
I will have a look at this :))

**Comment by kennytv** [comment]
https://github.com/HangarMC/Hangar/commit/877d939e0a0b96f2502171db2dda7b5e71096c6a
