### ISSUE TITLE
change logo link in navbar to hangar homepage

### ISSUE THREAD

**Issue by AwesomeDude091** [HangarMC/Hangar#570]
Not make papermc.io the Homepage link, it is slightly confusing. Make it so that Homepage is Hangar and then separately link PaperMC webpage

**Comment by kennytv** [comment]
+1 on that, Hangar shouldn't be seen as a simple subsection of the papermc.io website like a downloads section, but as its own place where you expect to get to the main Hangar page when clicking the logo.

**Comment by AwesomeDude091** [comment]
I could change this. Replying to help wanted tag
