### ISSUE TITLE
[Discussion] Replace user profile icon stuff with gravatar

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#576]
would allow us to save extreme amounts of code, any opposition to this?

**Comment by simpleauthority** [comment]
no opposition i have my gravatar set to the same thing i use everywhere else anyway

**Comment by mrsherobrine** [comment]
i don't quite see how you would handle it differently than project/group images, but it seems like a good idea

**Comment by felixoi** [comment]
I'm not a big fan of having to have a WordPress account to change a profile picture.

**Comment by kennytv** [comment]
> I'm not a big fan of having to have a WordPress account to change a profile picture.

I agree, this seems like a pretty annoying extra step for people that don't care to create yet another account on some external site

**Comment by OskarZyg** [comment]
imo you should provide both. I personally use gravatar, but some people wouldn't for one reason or another. Either way, wouldn't the image upload code still be there for orgs and projects?

**Comment by MiniDigger** [comment]
Orgs and projects are handled in hangar, not hangar auth, that's different

**Comment by AwesomeDude091** [comment]
But porting it over shouldn't be too crazy right? Or am I missing something critical here?

**Comment by Machine-Maker** [comment]
You can already set custom avatars on the auth side of things. I just am not sure I'm a big fan of the way I implemented it. Its very different (cause it sorta has to be) from the way changing icons for projects works.

**Comment by AwesomeDude091** [comment]
What is the (sorta has to be) part origin

**Comment by Machine-Maker** [comment]
Because we don't directly control the user database structure. that's handled via ory kratos.

**Comment by HeyBanditoz** [comment]
There is https://www.libravatar.org/ that can be used as a Gravatar alternative.

**Comment by AwesomeDude091** [comment]
I think this has the same flaw of registering at an alternate endpoint, separate from Hangar.

**Comment by emielderckx** [comment]
There is no way to delete a wordpress account. So I'm against using gravatar

https://backgroundchecks.org/justdeleteme/#Wordpress

**Comment by felixoi** [comment]
For me, the conclusion from all these comments so far is that we can add support for different "profile picture providers", but there still needs to be a way to set the profile picture manually without a third-party account or service.

**Comment by MiniDigger** [comment]
Yes, that's the conclusion, thanks everybody for their feedback
