### ISSUE TITLE
New Frontend: IntelliJ run configurations

### ISSUE THREAD

**Issue by AlessioGr** [HangarMC/Hangar#608]
Imma post my IntelliJ IDEA run configurations here (in the order in which I run it). Should be helpful as a reference for myself or others trying to run the Hangar project:
![image](https://user-images.githubusercontent.com/70709113/156478721-33271d89-18a9-4f98-b3c3-14b78782a2ef.png)

### 1. Docker:
![image](https://user-images.githubusercontent.com/70709113/156478742-0e342208-f50f-48dc-a33d-a66f449558ad.png)

### 2. Spring:
![image](https://user-images.githubusercontent.com/70709113/156478806-732145b2-ca22-42e3-ad9f-ecdef7d23f0a.png)

### 3. Frontend:
![image](https://user-images.githubusercontent.com/70709113/156478831-ee62e9e2-6bf7-459b-b9fa-36a00756f6dd.png)

### 4. (Optional) running the manual prettier fixing, in case it complains when you try to commit:
![image](https://user-images.githubusercontent.com/70709113/156478881-0667982b-8173-435a-827a-10fea13e7fe2.png)

So for new people trying to contribute: After cloning Hangar, downloading [Docker Desktop](https://www.docker.com/products/docker-desktop) and running `pnpm install` in the `new-frontend` folder, you can easily run Hangar with those run configurations.

**Comment by Scot-Survivor** [comment]
Just putting a comment here to say these configurations worked perfectly for me.

**Comment by MiniDigger** [comment]
fwiw, I did commit my run configs now (here and for auth). if there is anything else that can help people run stuff, it should be added to the readme
