### ISSUE TITLE
Question: Will users need to log in to download & Is anonymous downloading permitted via curl, etc...

### ISSUE THREAD

**Issue by tomlister** [HangarMC/Hangar#612]
Hi,

I'm wondering if a user could download a plugin jar anonymously through a curl or similar? I only ask because it appears a valid JWT is required to initiate a plugin download.

Cheers.

**Comment by Machine-Maker** [comment]
You don't have to be signed in to download a file. and yes there will be support for that if there isn't already.

**Comment by tomlister** [comment]
Thanks
