### ISSUE TITLE
Allow certain html tags in markdown pages

### ISSUE THREAD

**Issue by kennytv** [HangarMC/Hangar#633]
To allow finer control of text (and possibly other things) on the markdown pages, which some plugin devs use on other sites, we should look into allowing certain html tags in parsed markdown content. An example we likely will not get full parity but should at least look at is WorldEdit's use of tags [here](https://gist.github.com/me4502/0dcc648a065660777e370ddfa0433e3e)

**Comment by Exlll** [comment]
Please also enable support for spoilers:

```md
<details>
 <summary>Spoiler title</summary>

Spoiler content

</details>
```
