### ISSUE TITLE
Allow plugin pages to include bStats graphs.

### ISSUE THREAD

**Issue by Peter-Crawley** [HangarMC/Hangar#659]
bStats graphs are often shown on the Spigot Resources section *(example from EssentialsX's page below)*.

![Example](https://user-images.githubusercontent.com/49043380/169695904-e3f3c125-9780-4089-93e4-1641ebd003bf.png)

However these are are not interactable, it would be nice if these graphs were included on the plugin page itself.

**Comment by Intelli** [comment]
The issue is that SVG images don't seem to be supported.

https://hangarauth.papermc.io/image/https://bstats.org/signatures/bukkit/CoreProtect.svg

> {"status":{"code":500,"message":"Internal Server Error"},"message":"Could not extract response: no suitable HttpMessageConverter found for response type [class [B] and content type [image/svg+xml]","extra":{"stacktrace":["org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:126)","org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1043)","org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1026)","org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:784)","org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)","org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:367)","io.papermc.hangarauth.controller.ImageProxyController.proxy(ImageProxyController.java:44)","jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)","java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)","java.base/java.lang.reflect.Method.invoke(Unknown Source)","org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)","org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)","org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)","org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)","org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)","org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)","org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)","org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)","javax.servlet.http.HttpServlet.service(HttpServlet.java:497)","org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)","javax.servlet.http.HttpServlet.service(HttpServlet.java:584)","io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)","io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)","io.papermc.hangarauth.config.WebConfig$1.doFilterInternal(WebConfig.java:61)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)","io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)","io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)","org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)","org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)","org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)","org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)","org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)","org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)","org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)","org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)","org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)","org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)","org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)","io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)","io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)","org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)","io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)","io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)","org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)","org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)","io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)","io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)","io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)","io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)","io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)","io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)","io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)","io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)","io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)","io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)","io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)","io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)","io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)","io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)","io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)","io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)","io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)","io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)","io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)","io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)","io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)","io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)","io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)","io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)","io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)","io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)","io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)","io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)","io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)","org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)","org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)","org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)","org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)","org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)","java.base/java.lang.Thread.run(Unknown Source)"]}

**Comment by Intelli** [comment]
Created an image proxy in the meantime, that anyone is free to use: https://coreplugins.net/bstats-proxy/?project=CoreProtect

(Also has the added benefit of colour matching the background to the project page)

**Comment by olijeffers0n** [comment]
Appears to be fixed

**Comment by MiniDigger** [comment]
This is mostly about rendering dedicated, interactive graphs for bstats ourself, not the SVG ones provided by bstats, that was an unrelated bug

**Comment by kennytv** [comment]
Using the plain svgs seems good enough; if you want interactive graphs, those are one click away on the actual bstats graph (vs. us basically just re-implementing the same thing but worse)
