### ISSUE TITLE
fix crowdin

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/Hangar#687]
* add back the workflow to sync
* make it use the new json files
* somehow import the old strings? (maybe it does that automatically since it still knows the strings?)
* readd the in place editor thing
* add a language selector somewhere (that needs to save, like theme)
* clean unused language strings

**Comment by andrii-bodnar** [comment]
Hi @MiniDigger,

You could try to Pre-Translate the strings. If keys were not changed, then probably these translations will be matched with the translations in TM.

**Comment by felixoi** [comment]
Why you want to readd the syncing to GitHub?

**Comment by MiniDigger** [comment]
That was worded dum, just the action to pull when building
