### ISSUE TITLE
Deleting versions and then re-uploading fails. Also doesn't remove external download links

### ISSUE THREAD

**Issue by AlessioGr** [HangarMC/Hangar#691]
=> https://discord.com/channels/855123416889163777/859527399901626398/987885818683211796

If I soft-delete a version, I can not upload it again. There's a good chance of someone trying to re-upload the version and it thus failing.
I'd either exclude the soft-deleted versions from the duplicate checker, or disable the duplicate checker and just append something to the version (like a version, version-2, version-3).

Other issue:
The version I deleted was a recommended version with an external download link. After (soft)-deleting it, the external download link is still set for the main download button.

**Comment by Machine-Maker** [comment]
I think we should just make it so you don't need to delete a version and then add another one with the same name. Just edit what you want on that already existing version.

**Comment by kennytv** [comment]
Fixed with https://github.com/HangarMC/Hangar/commit/4b77ae63781dde0a080438e87f5e5405e682eca3
