### ISSUE TITLE
Unable to change icon of organisation

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#696]
I attempted to change the icon of my organisation [ArcanePlugins](https://hangar.benndorf.dev/ArcanePlugins), which resulted in an error notification saying `Unauthorised`.

**Comment by MiniDigger** [comment]
(this is just an issue with how a special secret is setup, not a code issue, will be cleaned up eventually when moving to new infra)

**Comment by MiniDigger** [comment]
fixed
