### ISSUE TITLE
Inconsistency in resource pages edit buttons

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#699]
To edit the `Docs` section of a resource page, the button is in the top right of the screen. However, this is not consistent with the sponsorships card edit button, which seems to be more appropriately placed on the top right of the card it is editing.

I believe the docs edit button should be on the top right of the docs card, akin to editing the sponsorships card.

**Comment by lokka30** [comment]
Seems to be fixed

**Comment by lokka30** [comment]
Nevermind, this seems to be a bug. I don't know how to reproduce it.

Firefox 101.0.1

**Comment by MiniDigger** [comment]
its a hydration error, backend doesn't render the button for some reason, frontend tries to fix it but misses a div
