### ISSUE TITLE
Markdown heading lines are too bright in dark mode

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#700]
In light mode, the heading lines of the resource docs pages are a light gray, so they don't have too much contrast, which is great. In dark mode, they are the same color as the text, so it has too much contrast. To improve this, the heading lines in dark mode should be darkened slightly.

[Example resource page](https://hangar.benndorf.dev/ArcanePlugins/LevelledMobs)

**Comment by MiniDigger** [comment]
all the text color is the same? we only have one dark mode text color that is used for all text
can you try to show a screenshot with what you mean? or do you suggest to generally change the dark mode text color?

**Comment by lokka30** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/59464084/174510880-a60c0b7b-2595-4feb-bba4-35f597b54e48.png">
<img width="895" alt="image" src="https://user-images.githubusercontent.com/59464084/174510897-7b12cf32-8320-474d-a464-0062139c8b68.png">
Notice how in light mode the heading lines are dull compared to the text. Hope this helps @MiniDigger :)

**Comment by MiniDigger** [comment]
oh you mean the line, lol
