### ISSUE TITLE
Error while filtering by version 

### ISSUE THREAD

**Issue by mastermc05** [HangarMC/Hangar#707]
![image](https://user-images.githubusercontent.com/63639746/174492685-b99274a8-ae6f-4cd7-a8df-1c4a595f4ab0.png)
happens on both check and uncheck the checkmark (i'm not logged in)

**Comment by MiniDigger** [comment]
those aren't errors. hangar tries to log you in but since you don't have a cookie that fails. the frontend can deal with that.
