### ISSUE TITLE
Implement Minecraft/Platform version filter on homepage

### ISSUE THREAD

**Issue by mastermc05** [HangarMC/Hangar#708]
thought it was because of https://github.com/HangarMC/Hangar/issues/707
but that filter then just doesn't work 
![image](https://user-images.githubusercontent.com/63639746/174493103-9cb51325-b1fa-4b50-96c9-3ec398f37010.png)
(i didn't see any 1.8 plugins still on the hangar, it should show nothing, other version filters also don't change the plugin list)

**Comment by MiniDigger** [comment]
mc version filter isn't implemented yet

**Comment by mastermc05** [comment]
oh, ok

**Comment by mastermc05** [comment]
but platform filter works, when filtering by velocity it doesn't show anything, by paper it shows all (i saw only paper plugins so i think it's ok)

**Comment by MiniDigger** [comment]
yep, all other filters I implemented friday night
issue is that mc version only applies to paper, since velocity and waterfall follow different rules, so I am not sure yet what to do here.

**Comment by kennytv** [comment]
Fixed in https://github.com/HangarMC/Hangar/commit/10c8d5eccfb41725b017d06670b4bebc2c7df97b
