### ISSUE TITLE
Reloading notifications page breaks styling

### ISSUE THREAD

**Issue by rtm516** [HangarMC/Hangar#709]
When the notifications page is reloaded (while being logged in) it shows a 401 for a split second then loads the boxes but the styling breaks and just stacks them

Before reload:
![image](https://user-images.githubusercontent.com/5401186/174495626-cd5e5acc-e052-4cae-a903-2392060268b1.png)

After reload:
![image](https://user-images.githubusercontent.com/5401186/174495608-b129755b-853e-467a-9c47-34d1969befad.png)

**Comment by kennytv** [comment]
Never seen that, it might have happened during deployment where everything breaks for half a minute?

**Comment by MiniDigger** [comment]
this is a hydration error that vue didn't recover nicely from
