### ISSUE TITLE
Feature Suggestion for Organisations

### ISSUE THREAD

**Issue by BlockyTheDev** [HangarMC/Hangar#710]
Either option to convert account to organisation (Or change username) or mention on the sign up page, that you don't need to create an account for an organisation, because of organisation creation feature. (Luckily I heard on the Discord that the accounts get deleted, when Hangar is going to be released, because I created an account for my organisation and after that I saw for the first time that there is an organisation feature.)

**Comment by kennytv** [comment]
Will be done as https://github.com/HangarMC/Hangar/issues/585
