### ISSUE TITLE
New page only listed after refresh

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#713]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/59464084/174513303-c5d08a86-f907-4b17-a0c2-8f18aa2b63fa.png">

I created a page called `Support`, but it didn't appear in the list of pages. [Link to resource page](https://hangar.benndorf.dev/ArcanePlugins/LevelledMobs)

**Comment by lokka30** [comment]
Nevermind, it appeared, but after a while. I'll leave this issue open if that's something that should be taken into interest

**Comment by MiniDigger** [comment]
pages in general have issues, switching between pages doesn't change the content for example. most likely a missing or wrong :key somewhere

**Comment by kennytv** [comment]
Page switching has been fixed with https://github.com/HangarMC/Hangar/commit/51e436d18cb955879df590b58f8598cdfe3b8acc, so only the update on page adding remains
