### ISSUE TITLE
Remove tags, make channel explicit part of a version, and add unstable attribute to channel

### ISSUE THREAD

**Issue by kennytv** [HangarMC/Hangar#716]
Version tags should be fully replaced with the already existing channel implementation to unify version metadata handling and make data accessing as well as assumptions about certain builds more explicit/obvious.

Version tags currently hold a version's channel, duplicated data about platforms, and whether it's unstable.

To replace them, we need to do the following:
  - The channel of a version should be stored in the version directly
  - Channels receive the extra attribute `unstable` (possibly more like `invite-only` in the future, set through a checkbox on channel creation/editing)
  - Platform versions can be accessed over the version and parsed as version ranges

**Comment by Machine-Maker** [comment]
I think we should just get rid of unstable and authors can make a channel for that right?

**Comment by kennytv** [comment]
Fixed in https://github.com/HangarMC/Hangar/commit/f503d64a62dcb72a8018063238af5b2d44d23f6b, https://github.com/HangarMC/Hangar/commit/f58c1f301134a28648825eee74af4dcbb3de1a02
