### ISSUE TITLE
Promoted and recommended versions

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#717]
I think this system should be unified and changed to simplify it from both an end-user and developer perspective. 

Recommended versions should be automatic, set via a checkbox on a channel (only 1 channel can have this checked). The latest version in that channel is the recommended version for that platform.

Promoted versions should become pinned versions. Users can pin a channel so the latest build from that channel is listed on the main project page, or users can pin a specific version that won't change unless removed.

Related: https://github.com/HangarMC/Hangar/issues/715

**Comment by kennytv** [comment]
Fixed in https://github.com/HangarMC/Hangar/commit/a3369d2d9e88e73e0ada99c0316b3117c1b25cbb, https://github.com/HangarMC/Hangar/commit/65bd042caa209a4c8ecd8e9753c36e8230be1f38
