### ISSUE TITLE
Allow for more control over project links

### ISSUE THREAD

**Issue by Machine-Maker** [HangarMC/Hangar#718]
There are now 5 project links:
* issues
* support
* homepage
* source
* wiki

We should have a more customizable system with those 5 as presets (and all disabled by default, except maybe source). Then users can add one of the presets or their own custom link. 

Limit at maybe... 7? not sure how many.

**Comment by MiniDigger** [comment]
I had a system in mind where we still limit the categories (cause the names need to be i18n technically and we can choose the icons, plus have consistency) but have the be just a map<linkcategory, link> or whatever so it can be easily extended.
