### ISSUE TITLE
Reset resource icon

### ISSUE THREAD

**Issue by SlimeDog** [HangarMC/Hangar#728]
I don't seem to be able to reset the resource icon (under Settings), once the resource has been submitted.

[for example](https://hangar.benndorf.dev/SlimeDog/AggressiveAnimals/settings)

[Choose file] doesn't work
[Reset Icon] doesn't work

**Comment by SlimeDog** [comment]
It turns out that the new image is stored, it just isn't displayed in the frontend. If I open the image in a new tab (right-click on the incorrectly-displayed image), the correct image is displayed in the new tab.

**Comment by kennytv** [comment]
That happens when you change/refresh there too often (due to caching:tm:), then fully reloading the page will get you the updated/reset one anyways
