### ISSUE TITLE
Early Hints (HTTP 103)

### ISSUE THREAD

**Issue by darbyjack** [HangarMC/Hangar#735]
### Is your feature request related to a problem?

Not a problem. Was talked about in the Discord. Possibly can improve response times. https://blog.cloudflare.com/early-hints-performance/

### Describe the solution you'd like.

Implement this please

### Describe alternatives you've considered.

Swimming in an olympic pool until this is added

**Comment by MiniDigger** [comment]
decided to not care for now, as I couldn't think of stuff we actually want to preload.
fwiw, once we do preload stuff, cloudflare will do this basically automatically, its only one button.
