### ISSUE TITLE
Clicked links hang

### ISSUE THREAD

**Issue by SlimeDog** [HangarMC/Hangar#746]
### Observed/problematic behavior

From an external page, left-click on [link to author page](https://hangar.benndorf.dev/SlimeDog) hangs. Right-click on same link, to open in a new tab/window, loads correctly.

Likewise, from [author page](https://hangar.benndorf.dev/SlimeDog), left-click on [link to resource page](https://hangar.benndorf.dev/SlimeDog/AggressiveAnimals) hangs. Spinner in upper right corner activates, but nothing else. Right-click on same link, to open in a new tab/window, loads correctly. Similarly for [link to someone else's resource page](https://hangar.benndorf.dev/pim16aap2/BigDoors).

Links in header -- Home, Authors, Team, etc. -- operate correctly.

### Expected behavior

Links should open when left-clicked.

### Steps to reproduce

MacOS Monterey 12.3.1 -- up-to-date
Safari 15.4 (17613.1.17.1.13) -- up-to-date
Safari extensions
- DuckDuckGo Privacy Dashboard
- DuckDuckGo Privacy Protection
- Ka-Block! ad-blocker

Load links as indicated above. Observe resulting behaviors.

Disabling extensions does not change the observed behaviors.

**Comment by MiniDigger** [comment]
What does your browser console say?

**Comment by kennytv** [comment]
Can reproduce, but *only* with your profile, also having nothing in the console :thonkeng: Yours and other resources just get the usual little hydration error that disappears when reloading, other profiles are also fine here

**Comment by SlimeDog** [comment]
Nothing in console.

**Comment by SlimeDog** [comment]
So what is different about my profile?

**Comment by kennytv** [comment]
Errm, on my iPhone in Safari/Chrome I can confirm the other issues with all project pages loading indefinitely unless you open in a new tab/full reload, and other profiles not properly loading either

**Comment by kennytv** [comment]
Profile and project page opening were fixed with https://github.com/HangarMC/Hangar/commit/51e436d18cb955879df590b58f8598cdfe3b8acc (only the hydration issue remains, but that's out of scope for this particular issue)

**Comment by SlimeDog** [comment]
Confirmed fixed on current dev server, without changes to my profile (afaik).
