### ISSUE TITLE
Auth issues

### ISSUE THREAD

**Issue by kennytv** [HangarMC/Hangar#765]
When not logged in, you're spammed with invalidate errors in the browser console.
Just go to any page/hit f5 when not logged into an account
![errors](https://i.imgur.com/lkpwYDO.png)

**Comment by lynxplay** [comment]
Hangar also fails to properly authenticate a user during a server side render.
This leads to an SSR render of any page in the context of an unauthenticated user. From this, hydration errors pop up like wildfire as the client side render properly handles authentication, leading to obvious differences between the SSR and CSR html.

An easy way to replicate this is by opening an href in a new tab.
1. Create the href in a gist for example: http://localhost:3333
2. Ctrl + left click it to open it in a new tab.
3. Enjoy hydration issues.

An even more visual replication step is doing the previous steps but with a page unauthed users would not have access to
[srr-does-not-auth.webm](https://user-images.githubusercontent.com/32834385/180460973-78b29b72-6ddc-474f-a04a-f0259f0420ce.webm)
