### ISSUE TITLE
Persist mainpage search filters when going back

### ISSUE THREAD

**Issue by Malfrador** [HangarMC/Hangar#828]
### Is your feature request related to a problem?

Currently, pressing the back button in your browser to return to the main page resets any entered search keywords and the page number. 

### Describe the solution you'd like.

Entered search terms and the page number should be part of the URL, so that the back function works properly.

### Describe alternatives you've considered.

Opening results in a new tab every time.

**Comment by MiniDigger** [comment]
maybe is fixed by having the filters be persisted in the url? maybe can be done together with #833
