### ISSUE TITLE
Downloads miscounted

### ISSUE THREAD

**Issue by kennytv** [HangarMC/Hangar#829]
Here, the top version was uploaded only a few minutes ago and only downloaded a handful of times but somehow got to 100 downloads.
![downlodas](https://i.imgur.com/Ha8pheS.png)

Could be because of having restarted the backend frequently while testing, but obv that shouldn't cause such an issue.

**Comment by ham1255** [comment]
not sure if this related but was testing download counts it does not seem to update on external links + uploaded jars

**Comment by MiniDigger** [comment]
It will never update instant, nor will it count external downloads.

**Comment by MiniDigger** [comment]
For s3 downloads maybe we just use redirects instead of cdn urls in frontend?

**Comment by MiniDigger** [comment]
test

**Comment by MiniDigger** [comment]
will be done via [#1040](https://github.com/HangarMC/Hangar/issues/1040) instead
