### ISSUE TITLE
clicking the button next on plugin upload page can trigger multi-upload if clicked twice or more

### ISSUE THREAD

**Issue by ham1255** [HangarMC/Hangar#831]
### Observed/problematic behavior

when uploading a plugin the button next can pressed twice which executes the Post request to the upload api and can cause weird behavior in the front-end can be seen in the video at Other section of the issue.

### Expected behavior

Next button function should be disabled until `Post` task is finished if one is exists, in-addition grey out the button.

### Steps to reproduce

* go to plugin upload section
* choose your plugin jar file 
* keep clicking `next` button

### Other

note: i just uploaded the paper jar to make upload process longer, which i thought the issue, no the issue can be triggered without need of giant jar file.

tested browsers: `firefox`, `google chrome`

video showing Debug menu in google chrome in Network tab

https://user-images.githubusercontent.com/34905970/182512375-14e51363-e5c1-4167-b695-4d9f867e9705.mp4

**Comment by kennytv** [comment]
Fixed with https://github.com/HangarMC/HangarLib/commit/32533a86086a74b62d6f9165fdea2546cb706d7c, though probably won't be deployed on the current staging instance
