### ISSUE TITLE
Update supported MC versions

### ISSUE THREAD

**Issue by Andre601** [HangarMC/Hangar#832]
### Is your feature request related to a problem?

Currently, the following versions are the latest supported by Hangar to display on releases:

- PaperMC: 1.19
- Waterfall: 1.18

These are obviously outdated.

### Describe the solution you'd like.

Just add the latest 1.19 and 1.19.1 versions to the supported versions for releases for PaperMC and Waterfall.

### Describe alternatives you've considered.

There aren't any.

**Comment by kennytv** [comment]
Doesn't matter, will be changed with the proper staging instance
