### ISSUE TITLE
Finish API for uploading versions

### ISSUE THREAD

**Issue by zml2008** [HangarMC/Hangar#941]
### Is your feature request related to a problem?

It should be possible to headlessly upload versions to Hangar -- via Gradle, a CLI client, or any sort of other tools.

There is some WIP stubs for this API already, but no issue tracking its completion

### Describe the solution you'd like.

Finish the WIP at https://github.com/HangarMC/Hangar/blob/b499f125d6d6dbf28d8f9aa2f789e145ad5b2cc0/backend/src/main/java/io/papermc/hangar/controller/api/v1/interfaces/IVersionsController.java#L30

### Describe alternatives you've considered.

meow

**Comment by kennytv** [comment]
Docs will need to be extended/fixed, but here's an example of this first version in action using the following endpoint:
https://hangar.papermc.dev/api-docs#/Versions/uploadVersion as a `multipart/form-data` post request containing `versionUpload` data and an optional list of files (as `files`, one file for each platform you didn't specify `externalUrl` in the version data):
```json
{
  "versionString": "1.0.0",
  "pluginDependencies": {
    "PAPER": [
      {
        "name": "Something",
        "required": true,
        "namespace": {
          "owner": "paper",
          "slug": "Maintenance2"
        }
      },
      {
        "name": "ViaVersion",
        "required": true,
        "externalUrl": "https://hangar.papermc.io/ViaVersion/ViaVersion"
      }
    ],
    "WATERFALL": [

    ]
  },
  "platformDependencies": {
    "PAPER": [
      "1.18",
      "1.19"
    ],
    "WATERFALL": [
      "1.19"
    ]
  },
  "files": [
    {
      "platforms": [
        "PAPER"
      ]
    },
    {
      "platforms": [
        "WATERFALL"
      ],
      "externalUrl": "https://twitter.com/"
    }
  ],
  "channel": "Release",
  "description": "My cool description!"
}
```
